### ISSUE TITLE
Sharpe Ratio not fetched correctly

### ISSUE THREAD

**Issue by riodda** [akumidv/tradingview-assistant-chrome-extension#10]
I was trying to optimize a strategy on sharpe ratio but look like the assistant is unable to fetch it corectly.
![image](https://user-images.githubusercontent.com/13453063/153827365-8e7edc4f-7d99-4691-8651-4bbb62b552e5.png)

**Comment by akumidv** [comment]
> I was trying to optimize a strategy on sharpe ratio but look like the assistant is unable to fetch it corectly. ![image](https://user-images.githubusercontent.com/13453063/153827365-8e7edc4f-7d99-4691-8651-4bbb62b552e5.png)

Thanks for your issue. I'll check and fix in next version if this. Another screenshot from the console in developer mode would help. (F12)
But in general, this does not look like a Sharp Ratio problem, because this result is obtained, just like all the others.

**Comment by akumidv** [comment]
Also changed in new version after changes in TV UI.
