### ISSUE TITLE
Banned accounts from Tradingview (maybe it's my fault).

### ISSUE THREAD

**Issue by MarNery** [akumidv/tradingview-assistant-chrome-extension#101]
Sorry, this may sound crazy, but I work for a company that will invest a percentage of money in stocks of various companies. But to do this they are thoroughly studying each stock like: technical analysis (intraday to hold), fundamental analysis and so many other areas that you already know. 

I was chosen to present the data of a somewhat complex strategy. This strategy has at least 52000 different combinations in each timeframe. 
Note: If you use all the options, the number of combinations exceeds 1 million combinations (yes I also think this is too big).

It was not required the maximum number of combinations (that would be an exaggeration), but it was required to test at least 52000 combinations.

I need the backtest results at 1h, 2h, 3h, 4h and 1D. This causes the extension to run over 260,000 tests on each stock that I need to backtest.

To speed up the process, I open 10 Brave windows and configure the extension data in each Brave window to have 5200 combinations in each timeframe. As there are 5 timeframes, the total sum is 26000 combinations (5200 in 1h + 5200 in 2h + 5200 in 3h + 5200 in 4h + 5200 in 1D).

The extension is set to do 1 query per second and wait 3 seconds on "errors".

Yes. I know that the numbers I showed you are high, and that this may be interfering with the banning of my TV accounts but I don't see any other alternative.

I have already lost 2 (free) accounts on tradingview for "suspicious activities", before even finishing the first backtest on the 1h timeframe.

I need to do each backtest of the above in 120 stocks until the end of March to present to the managers all the possible configurations of the "profit factor" of each stock.

For this I am willing to rent some VMs on Google Cloud and create several accounts on tradingview.

I am having a big problem and need help from you guys.

How do I do a complete backtest, without getting banned before the backtest finishes successfully and the .csv file with the results is generated!?

**Comment by akumidv** [comment]
> Sorry, this may sound crazy, but I work for a company that will invest a percentage of money in stocks of various companies. But to do this they are thoroughly studying each stock like: technical analysis (intraday to hold), fundamental analysis and so many other areas that you already know.
> ...
> How do I do a complete backtest, without getting banned before the backtest finishes successfully and the .csv file with the results is generated!?

You can convert your Tradingview strategy to python and run all tests as you wish.
If you really have in mind about quality - it is only way, because TV data is limited, the speed is slow to test real number of parameters and so on.

**Comment by MarNery** [comment]
Thanks for the answer.
After converting the strategy to Phyton, which application can I backtest faster?

**Comment by MrDenfish** [comment]
Wow, seems like you have a giant can of worms to sort out. The following link may help some, but I think there is going to  be a bit of learning curve.  Anyhow, check out the link, lots of possible Github communities that may be of help.  
If you get it sorted out and have time, I'd be interested in hearing the results. I have always been interested in going the python route but have not had the time.

Good luck,
Df
https://www.quantstart.com/articles/backtesting-systematic-trading-strategies-in-python-considerations-and-open-source-frameworks/

**Comment by akumidv** [comment]
> Thanks for the answer.
> After converting the strategy to Phyton, which application can I backtest faster?

It depends on how the strategy will be converted. Usually it can be run directly from the command line, most often on a server or several of them. Depends of strategy and goals that you persuit.
The conversion should solve the problem of obtaining data, backtesting the strategy and optimizing the parameters, showing and storing results.

**Comment by Camilo-Mora** [comment]
Do we know what is the limit of times one can run the optimizer?

**Comment by orlagwon** [comment]
> Do we know what is the limit of times one can run the optimizer?

Have you tested how many?
