### ISSUE TITLE
using a proxy

### ISSUE THREAD

**Issue by synthesis1apex** [akumidv/tradingview-assistant-chrome-extension#103]
hi thank you for making this extension do you think it would help to run a rotating proxy when performing the back test to limit the risk of getting band?
thanks

**Comment by akumidv** [comment]
I'm sure in Tradingview developer use account id for checking requests limit  and do not IP. So proxy rotation more probably do not help.

**Comment by synthesis1apex** [comment]
thanks!!! so the only way is to convert to python? like you said in the recommendations

**Comment by synthesis1apex** [comment]
just tried it out that delay feature is genius! everythings working great thanks so much!
