### ISSUE TITLE
Error Message: "TypeError: Cannot convert undefined or null to object"

### ISSUE THREAD

**Issue by vanmoog** [akumidv/tradingview-assistant-chrome-extension#108]
Hi guys,

I seemingly found a bug which only occurs when I want to Deep Backtest.

It startet some minutes ago and it says

"TypeError: Cannot convert undefined or null to object"
![Screenshot (1)](https://user-images.githubusercontent.com/112553656/230207959-8a89d14d-4d8d-432f-85bd-9757919f5c03.png)

Thanks!

**Comment by akumidv** [comment]
The problem on init stage. It will be very helpful if you open browse developer console (press F12) and take screenshot with expanded row with error. That I can found this problem faster.

**Comment by vanmoog** [comment]
Thanks for your help mate. I've screenshoted the error message on the console. Hope this helps to solve the problem:
<img width="425" alt="TV bug" src="https://user-images.githubusercontent.com/112553656/230603756-7238711b-2587-4841-89d4-26b2ac0bb382.png">

**Comment by vanmoog** [comment]
I have a suggestion why this is happening. Maybe the script is missing that you have to deactivate and reactivate the deep backtesting button in order apply the new parameter settings to the strategy...

**Comment by akumidv** [comment]
Can you increase waiting time on Option&Tools tab from 30 sec to 60sec or more. Probably you strategy calculation demand more time than 30 sec.
