### ISSUE TITLE
Update Sample template

### ISSUE THREAD

**Issue by kokoulin** [akumidv/tradingview-assistant-chrome-extension#11]
сбстн сабж, в линке зашит шаблон без default и priority
и если возможно добавьте описание этих полей

**Comment by akumidv** [comment]
> сбстн сабж, в линке зашит шаблон без default и priority и если возможно добавьте описание этих полей

Ok. В следующей версии в начала марта планируется.

**Comment by akumidv** [comment]
implemented in code, but not included in new version. Will be updated in new version.
