### ISSUE TITLE
error message "isIndicatorSave is not defined" for Get Template

### ISSUE THREAD

**Issue by leolo12345** [akumidv/tradingview-assistant-chrome-extension#110]
Click Get Template
It show error message "isIndicatorSave is not defined"
![error](https://user-images.githubusercontent.com/109061691/230706881-06ff5e47-f00d-4cd7-b552-1332f6c78f31.gif)

**Comment by akumidv** [comment]
Thank you. Fixed in version 2.5. I sent it to review in Google WebStore. Probably will be published tomorrow.

This problem occurred for dropdown values. If you skip them from optimization parameters this error will not stop baktesitng process.

**Comment by leolo12345** [comment]
Thanks akumidv, i fixed it
