### ISSUE TITLE
How can I get version 2.5 in zip?, thanks

### ISSUE THREAD

**Issue by Camilo3110** [akumidv/tradingview-assistant-chrome-extension#113]
How can I get version 2.5 in zip?, thanks

**Comment by stefantabakovq** [comment]
Add it from Chrome store since it is not updated here, you can find it at `C:\Users\[login_name]\AppData\Local\Google\Chrome\User Data\Default\Extensions`

**Comment by akumidv** [comment]
I didn't publish these changes because working on new 3.0 version with some critical changes in parameters storage logic. 
But for now some these selector changes isolated and published as version 2.6 https://github.com/akumidv/tradingview-assistant-chrome-extension/releases/tag/v2.6
