### ISSUE TITLE
UI Changed again (17.04.2023)

### ISSUE THREAD

**Issue by stefantabakovq** [akumidv/tradingview-assistant-chrome-extension#114]
Some intern at TV has had the busiest week.

 Seems to be fixed by changing `strategyTesterTab` to `strategyTesterTab: '#bottom-area > div.bottom-widgetbar-content.backtesting'` in `selector.js`.

**Comment by thecao365** [comment]
![image](https://user-images.githubusercontent.com/4857521/232484600-2f4622e4-385c-42de-b65a-1dccf129b327.png)
![image](https://user-images.githubusercontent.com/4857521/232484632-b45e48dc-2290-461d-a0f4-88d303e54af5.png)

I got an additional error after following the instructions above.

**Comment by stefantabakovq** [comment]
> ![image](https://user-images.githubusercontent.com/4857521/232484600-2f4622e4-385c-42de-b65a-1dccf129b327.png) ![image](https://user-images.githubusercontent.com/4857521/232484632-b45e48dc-2290-461d-a0f4-88d303e54af5.png)
> 
> I got an additional error after following the instructions above.

Make sure you are using content_scripts folder as of version 2.5. You can get version 2.5 by adding it via Chrome Web store, then navigate to `C:\Users\[login_name]\AppData\Local\Google\Chrome\User Data\Default\Extensions` and get the folder from there!
Then in selector.js, update only this line, make sure that there is a comma afterwards. Don't know what other issue it could be.
