### ISSUE TITLE
TradingView-Ban

### ISSUE THREAD

**Issue by kipler1** [akumidv/tradingview-assistant-chrome-extension#115]
Hey everyone, 
I was wondering if someone knows the limitation of using this tool.
Yesterday I ran it in 6 browsers simultaneously with 2000 repeats which lead to a short ban about 2 hours.
Now I'm kinda scared and wanted to ask how much u guys let it run and on how many repeats also has anybody knowledge 
if I'm now flagged in the trading view system ?

**Comment by akumidv** [comment]
I guess usage of 6 browsers is not usual. You can  try next time work from one IP with one tradingview ID. 
This is not exactly limitation of tool. It's TradingView rules. This extension is mostly for check some simple hypothesis. If you need to use industrial methods for optimization some strategies - there is only one way - converting strategy to python, get source data and run it on the your virtual server.

**Comment by orlagwon** [comment]
> Hey everyone, I was wondering if someone knows the limitation of using this tool. Yesterday I ran it in 6 browsers simultaneously with 2000 repeats which lead to a short ban about 2 hours. Now I'm kinda scared and wanted to ask how much u guys let it run and on how many repeats also has anybody knowledge if I'm now flagged in the trading view system ?

Have you tried less combinations? How was that?
