### ISSUE TITLE
UI Changed Again

### ISSUE THREAD

**Issue by beetabpilot** [akumidv/tradingview-assistant-chrome-extension#116]
TV has once again changed UI rendering the extension unusable, as of this morning, 4/17/23.

**Comment by stefantabakovq** [comment]
#114

**Comment by beetabpilot** [comment]
> #114

Appreciate the assistance.  I tried your fix, but it didnt appear to work.  Still getting the same error.

**Comment by mpetrishchev** [comment]
The same problem, #116 didn't fix

**Comment by Quetzalquatl** [comment]
Replace the following lines in selector.js with newliness

original lines:

trategyTesterTab: '#footer-chart-panel div[data-name="backtesting"]',
strategyTesterTabActive: '#footer-chart-panel div[data-name="backtesting"][data-active="true"]',

new lines:
strategyTesterTab: '#bottom-area div[class^="backtesting"]',
strategyTesterTabActive: '#bottom-area div[class^="backtesting"][data-active="true"]',

**Comment by RedOldBoy** [comment]
> Replace the following lines in selector.js with newliness
> 
> original lines:
> 
> trategyTesterTab: '#footer-chart-panel div[data-name="backtesting"]', strategyTesterTabActive: '#footer-chart-panel div[data-name="backtesting"][data-active="true"]',
> 
> new lines: strategyTesterTab: '#bottom-area div[class^="backtesting"]', strategyTesterTabActive: '#bottom-area div[class^="backtesting"][data-active="true"]',

Hello can you quickly guide me how to this changes, where to, ect
thank you!

**Comment by Quetzalquatl** [comment]
@RedOldBoy Download files (zip), edit content_scripts > selector.js with the changes above, then go to 'chrome://extensions' > Load unpacked and select files folder. Remove old version first though (it will wipe your settings unfortunately)

**Comment by Quetzalquatl** [comment]
tradingview has changed it again

**Comment by RedOldBoy** [comment]
> @RedOldBoy Download files (zip), edit content_scripts > selector.js with the changes above, then go to 'chrome://extensions' > Load unpacked and select files folder. Remove old version first though (it will wipe your settings unfortunately)

Thank you for your fast reply, I done everything as you indicated but still get "there is not strategy parameters input Tab. test stopped, open correct tab" 
any idea why ?

**Comment by Quetzalquatl** [comment]
Can you share a screenshot of the error?

**Comment by Quetzalquatl** [comment]
This error is not the same as the previous error. Follow the steps as before..

tabInput: 'div[data-name="indicator-properties-dialog"] div[data-value="inputs"]',
tabInputActive: 'div[data-name="indicator-properties-dialog"] div[class*="active"][data-value="inputs"]',

**Comment by RedOldBoy** [comment]
> This error is not the same as the previous error. Follow the steps as before..
> 
> tabInput: 'div[data-name="indicator-properties-dialog"] div[data-value="inputs"]', tabInputActive: 'div[data-name="indicator-properties-dialog"] div[class*="active"][data-value="inputs"]',

hello again, just did the last step but still have the same 
![Screenshot 2023-04-18 013048](https://user-images.githubusercontent.com/129317301/232646731-78ddcc36-814d-493f-b09f-3bf13ef6f5f9.jpeg)
error message

**Comment by Quetzalquatl** [comment]
@RedOldBoy replace related lines:

tabInput: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs',
tabInputActive: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs[class*="selected"]',
tabProperties: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#properties',

strategyTesterTab: '#bottom-area div[class^="backtesting"]',
strategyTesterTabActive: '#bottom-area div[class^="backtesting"][data-active="true"]',

**Comment by RedOldBoy** [comment]
> @RedOldBoy replace related lines:
> 
> tabInput: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs', tabInputActive: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs[class*="selected"]', tabProperties: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#properties',
> 
> strategyTesterTab: '#bottom-area div[class^="backtesting"]', strategyTesterTabActive: '#bottom-area div[class^="backtesting"][data-active="true"]',

This has solved the problem, thanks a lot for your time!
Is this a common complication ?

**Comment by X48Github01** [comment]
> @RedOldBoy replace related lines:
> 
> tabInput: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs', tabInputActive: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs[class*="selected"]', tabProperties: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#properties',
> 
> strategyTesterTab: '#bottom-area div[class^="backtesting"]', strategyTesterTabActive: '#bottom-area div[class^="backtesting"][data-active="true"]',

Oh 💖😍😍 Thanks a lot 💖💖 it's work

**Comment by mpetrishchev** [comment]
I've done it, but the problem didn't fix.... Any idea? 

![Err](https://user-images.githubusercontent.com/106669970/232674643-602f7029-b43b-42f3-bf07-ca83d2f9d62a.JPG)

**Comment by caddycady** [comment]
> 

how can i open zip files i didnt understand steps

**Comment by stefantabakovq** [comment]
> > 
> 
> how can i open zip files i didnt understand steps

https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/heads/main.zip

**Comment by caddycady** [comment]
thx. but i cant change selector.js how can i open and fix the codes in this folder

**Comment by s3xmaxman** [comment]
[tradingview-assistant-chrome-extension-main.zip](https://github.com/akumidv/tradingview-assistant-chrome-extension/files/11261527/tradingview-assistant-chrome-extension-main.zip)
Modified file. It works in my environment.

**Comment by caddycady** [comment]
i couldnt do i am waiting official fix

**Comment by MrDenfish** [comment]
> 

This works for me (windows pc)  replace the three highlighted lines of code  with:

tabInput: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]',
tabInputActive: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]',
tabProperties: 'div[data-name="indicator-properties-dialog"] button#properties',

![Screenshot 2023-04-18 071458](https://user-images.githubusercontent.com/108489215/232823980-0585edbf-89a3-4f2c-bd2e-d9544e4fa464.png)

...and yes this is a regular event, but  the small amount of inconvenience is well worth it.  The extension is fantastic!!

**Comment by caddycady** [comment]
okey but what did do with this code i did same think

**Comment by caddycady** [comment]
can someone write step step how to upload this fixed code please

**Comment by stefantabakovq** [comment]
> can someone write step step how to upload this fixed code please

Chrome -> type chrome://extensions -> top right slider Developer Mode ON -> Load unpacked; Select unzipped folder (remove old extension first) -> refresh TV page should be working

**Comment by g001613001** [comment]
> [tradingview-assistant-chrome-extension-main.zip](https://github.com/akumidv/tradingview-assistant-chrome-extension/files/11261527/tradingview-assistant-chrome-extension-main.zip) Modified file. It works in my environment.

It's works for me, thanks.

**Comment by mpetrishchev** [comment]
> [tradingview-assistant-chrome-extension-main.zip](https://github.com/akumidv/tradingview-assistant-chrome-extension/files/11261527/tradingview-assistant-chrome-extension-main.zip) Modified file. It works in my environment.

Works, thanks!

**Comment by dangquang1506** [comment]
> @RedOldBoy replace related lines:
> 
> tabInput: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs', tabInputActive: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#inputs[class*="selected"]', tabProperties: '#overlap-manager-root div[data-name="indicator-properties-dialog"] [class^="tab"] button#properties',
> 
> strategyTesterTab: '#bottom-area div[class^="backtesting"]', strategyTesterTabActive: '#bottom-area div[class^="backtesting"][data-active="true"]',

Many thanks bro. I did it. So appreciate. Thanks for your help.

**Comment by akumidv** [comment]
I'll recheck current selectors. It seems work on my Tradingview UI version. They probably publish early UI version for some  regions. I've changed some selectors as it described above and sent version to publish in Google WebStore.

**Comment by dangquang1506** [comment]
> > This error is not the same as the previous error. Follow the steps as before..
> > tabInput: 'div[data-name="indicator-properties-dialog"] div[data-value="inputs"]', tabInputActive: 'div[data-name="indicator-properties-dialog"] div[class*="active"][data-value="inputs"]',
> 
> hello again, just did the last step but still have the same error with another one hidden behind it ![image_2023-04-18_013713912](https://user-images.githubusercontent.com/129317301/232647083-089bca54-183a-4b4f-aa94-55dc0637bea5.png)
> 
> ![Screenshot 2023-04-18 013048](https://user-images.githubusercontent.com/129317301/232646731-78ddcc36-814d-493f-b09f-3bf13ef6f5f9.jpeg) error message

Can we edit in the code that after run the test that the tool will automatic download the report data to our computer? Sometimes i run the tool, it takes about more than 10 hours, but when i was slept, the tool finish but sometimes when wrong with my computer, so i can not download the report file. So i have to run the test again and wait. It really take time :(
Can you help me where to edit the code?

**Comment by B0gdan2K** [comment]
> > 
> 
> This works for me (windows pc) replace the three highlighted lines of code with:
> 
> tabInput: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]', tabInputActive: 'div[data-name="indicator-properties-dialog"] button[id="inputs"]', tabProperties: 'div[data-name="indicator-properties-dialog"] button#properties',
> 
> ![Screenshot 2023-04-18 071458](https://user-images.githubusercontent.com/108489215/232823980-0585edbf-89a3-4f2c-bd2e-d9544e4fa464.png)
> 
> ...and yes this is a regular event, but the small amount of inconvenience is well worth it. The extension is fantastic!!

Hi, this worked for me, thanks!
