### ISSUE TITLE
Regarding the issue of v2.6 deep backtesting frequently getting stuck

### ISSUE THREAD

**Issue by g001613001** [akumidv/tradingview-assistant-chrome-extension#118]
v2.6 I am running a 30-minute BTC deep backtest on Binance, from the earliest to the current date, and it seems that I often can't press the "Generate Report" button, so it gets stuck and doesn't move. So currently, I've reverted to the v2.3 version provided by another user. I wonder if anyone else is having the same issue with the updated v2.6 version?

**Comment by akumidv** [comment]
I'll double check deep backtesting. Probably on this weekend I have time

**Comment by akumidv** [comment]
In v2.8.1 there some fixes for backtesting that can help for some strategies where generation report button is not set clickable fast after the strategy parameters are changed.
Can you check?
