### ISSUE TITLE
Increase Cycles limit

### ISSUE THREAD

**Issue by mtahreemalam** [akumidv/tradingview-assistant-chrome-extension#12]
Hello, Love your extension.
Is there a possibility to test all input parameters with permutation not sequential to be able to test all possible combinations?

**Comment by akumidv** [comment]
Hi, thanks for you comment. 
There are no limitations in extension, but in the current version there are no strategies that make sense to run with so many tests. Random method is randomly iterates through the parameters from the best position found and it will sort through the same options. I plan to release a new version next week. It will generate completely random parameters with this method it can have sense run such large tests.

**Comment by mtahreemalam** [comment]
Sorry to bug, i know you are a busy man. This is the last query.
I basically want to test all possible input parameters permutation of a particular strategy. 
Lets say a Super Trend with SL, the total permutations would be below (i.e. 30k):
	From	To	Steps			Number of Outputs
Factor	1	3	0.1			30
Period	1	20	1			20
Stop Loss	0.1	5	0.1			50
					Total Permutations	 30,000 

If i run this on sequential it determines a 71 cycle iteration and not 30k which is the actual number of permutations.
How should i make it work?

**Comment by mtahreemalam** [comment]
> Hi, thanks for you comment. There are no limitations in extension, but in the current version there are no strategies that make sense to run with so many tests. Random method is randomly iterates through the parameters from the best position found and it will sort through the same options. I plan to release a new version next week. It will generate completely random parameters with this method it can have sense run such large tests.

Hey,
Has the new version been released? 
I would like to hire you for some customization. Where can we discuss the requirements?

**Comment by akumidv** [comment]
> Hey, Has the new version been released? I would like to hire you for some customization. Where can we discuss the requirements?

Hey, not yet. It was very busy two weeks in Russian. I'll try on weekend. You can message me on facebook http://facebook.com/akuminov I'll reply with my other contacts.

**Comment by mtahreemalam** [comment]
> > Hey, Has the new version been released? I would like to hire you for some customization. Where can we discuss the requirements?
> 
> Hey, not yet. It was very busy two weeks in Russian. I'll try on weekend. You can message me on facebook http://facebook.com/akuminov I'll reply with my other contacts.

I have left you a text on facebook messenger

**Comment by 4while** [comment]
Your extension and this type of strategy testing is under-rated.
I noticed that too.
For this reason i start with a take profit and leave a huge stop loss
When a good TP is found the next parameter is the Stop Loss

**Comment by akumidv** [comment]
In new 1.3 version implemented brute force method.
