### ISSUE TITLE
Problems with deep backtesting

### ISSUE THREAD

**Issue by TradingCD23** [akumidv/tradingview-assistant-chrome-extension#120]
Hello, I hope you are very well.
In advance to congratulate you is a great job.

I wanted to tell you that when I do the brute force optimization in deep backtesting I am having a problem and that is that the values ​​in the rows of the accumulated file are repeated, it seems that there are cycles that skip them and put the results of the previous one. What could I do. Thank you very much for your help!!

**Comment by trading-ar** [comment]
Having the same issue ....

**Comment by akumidv** [comment]
Thanks, I'm preparing new major version and planned to fix this problem in it.

**Comment by akumidv** [comment]
Can you try to increase time between test in options?
Also in new 2.8.1 version the extension check is button for "Generation report" is clickable (or disabled). Probably in version before - it just not set clickable after changing in parameters - and click for new test just missed and parser grab the previous result.
So please check in new 2.8.1 version that I sent to Google Web-Store today
