### ISSUE TITLE
Deep Backtesting is not working.

### ISSUE THREAD

**Issue by vanmoog** [akumidv/tradingview-assistant-chrome-extension#123]
Hey there,
I hope this message finds you well!

First of all thank you for your amazing job!!

I just wanted to report that deep backtesting is not working. Propaply TV changed again the HTML code?
It has the same issue as previously. It rushes through the testing iterations and doesnt wait for the actual result.

Thank you in advance!

**Comment by akumidv** [comment]
Yes, backtesting UI changed. I'll fix this.

**Comment by akumidv** [comment]
The deep backtesting behavior to generate new strategy report is changed in new 2.8.1 version. Can you check?
