### ISSUE TITLE
"No strategy name element" error persists, due to TV UI changes

### ISSUE THREAD

**Issue by kypexin** [akumidv/tradingview-assistant-chrome-extension#124]
Hello,

I am not sure that there might have been any other changes to TV UI, but for the last week I was not able to get the Assistant to work, whatever patch suggested in the latest threadsI tried to apply. It still says 'No strategy tester' for me.

![Screenshot 2023-05-08 at 22 02 32](https://user-images.githubusercontent.com/10047776/236911604-e0064a36-fb08-45f4-9f3e-f9cf3e238084.png)

Any ideas where the root cause might be? I have tried different older versions of extension as well, all to no avail.

**Comment by kypexin** [comment]
No one else experiences this error?
I got back to check, but as soon as there were no new versions, the extension is still not working for me as of now.

**Comment by akumidv** [comment]
The problem is reproduced when reload TV page and before the strategy elements are loaded. I'll add timeout to wait till they loading will be finished.

**Comment by akumidv** [comment]
In v2.8 add waiting for strategy tab elements.
