### ISSUE TITLE
Deep Backtesting Error

### ISSUE THREAD

**Issue by sshivinn37** [akumidv/tradingview-assistant-chrome-extension#128]
Deep Backtesting is not changing the parameters and therefore does not allow the backtest. Would really appreciate your support in this. Btw, extremely well designed tool! Cheers

**Comment by g001613001** [comment]
I also encountered the same problem, I can't use the deep backtesting function anymore...

**Comment by akumidv** [comment]
Yeah, this error reproduced. I'm working on it.

**Comment by g001613001** [comment]
> Yeah, this error reproduced. I'm working on it.

"I have encountered this problem many times. Currently, one solution is to reselect the start date or the end date, which can restore the button to a clickable state. I'm sharing this for your reference."

**Comment by akumidv** [comment]
The problem with changing parameters was not reproduced. But the deep backtesting behavior for generate new strategy report is changed in new 2.8.1 version. Can you check?
