### ISSUE TITLE
Possible to schedule running on cloud?

### ISSUE THREAD

**Issue by mtahreemalam** [akumidv/tradingview-assistant-chrome-extension#13]
Hey,
Like alot of chrome extensions allow scraping on cloud, can we customize this as a paid feature for users?

**Comment by akumidv** [comment]
This is a different technology, it needs to be run not as an extension, but through browser via puppeteer. Yes, it can be done, but the user will have to give credential data for authorization through his account and also this method demand to implement the environment setting - i.e. add a strategy to the chart.

But the implementation of such a method as a commercial technology will be limited, it will create a hiload on the tradingview cloud and I am sure they will block ip.
