### ISSUE TITLE
Some columns don't show in file when "backtesting the strategy on timeframes (divided by comma)" is selected

### ISSUE THREAD

**Issue by GitHub1m** [akumidv/tradingview-assistant-chrome-extension#133]
Some columns don't show in exported file when "Backtesting the strategy on timeframes (divided by comma)" is selected. "Avg Trade: Long %", and "Avg Trade: Short %" are some columns that don't show.

**Comment by akumidv** [comment]
Thanks, I'll check

**Comment by akumidv** [comment]
Can't reproduce this error. In current 2.8.1 version all working correct. Can  you check on some simple strategy, like MACD or SMA cross and check?
