### ISSUE TITLE
Error: There is not timeframe element on page. Open correct page please

### ISSUE THREAD

**Issue by g001613001** [akumidv/tradingview-assistant-chrome-extension#134]
New bug, please fix it, thank you.
Thank you!
![截圖 2023-06-20 下午8 41 18](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/18544298/f44a9b70-b3cc-4bc4-9098-8dc2a1e21191)

**Comment by kipler1** [comment]
Anybody knows When there will be a fix ?

**Comment by maben1975** [comment]
I also encountered this bug too.

**Comment by oblachnov** [comment]
Yes, stopped working completely

**Comment by Chesteer89** [comment]
Just update the selectors:
```
    chartTimeframeFavorite: '#header-toolbar-intervals div[role="radio"]',
    chartTimeframeActive: '#header-toolbar-intervals div[role="radio"][data-value][aria-checked="true"]',
    chartTimeframeMenuOrSingle: '#header-toolbar-intervals div[class^="menu"]',
```

**Comment by dannydanny77** [comment]
> Just update the selectors:
> 
> ```
>     chartTimeframeFavorite: '#header-toolbar-intervals div[role="radio"]',
>     chartTimeframeActive: '#header-toolbar-intervals div[role="radio"][data-value][aria-checked="true"]',
>     chartTimeframeMenuOrSingle: '#header-toolbar-intervals div[class^="menu"]',
> ```

This works perfectly... Thanks very much for the help...
Cheers.

**Comment by akumidv** [comment]
This error was fixes in version 2.7 - it was send to review and publish in webstroe

**Comment by TheLichKing60** [comment]
broke again... f*** TV

**Comment by TheLichKing60** [comment]
can anybody send screens of how to do this? 
chartTimeframeFavorite: '#header-toolbar-intervals div[role="radio"]',
chartTimeframeActive: '#header-toolbar-intervals div[role="radio"][data-value][aria-checked="true"]',
chartTimeframeMenuOrSingle: '#header-toolbar-intervals div[class^="menu"]',

**Comment by maben1975** [comment]
> Just update the selectors:
> ```
>     chartTimeframeFavorite: '#header-toolbar-intervals div[role="radio"]',
>     chartTimeframeActive: '#header-toolbar-intervals div[role="radio"][data-value][aria-checked="true"]',
>     chartTimeframeMenuOrSingle: '#header-toolbar-intervals div[class^="menu"]',
> ```

it running ok. great thanks

**Comment by TheLichKing60** [comment]
Just update the selectors: how?

**Comment by TheLichKing60** [comment]
its not working for me...

**Comment by AlexProMoney** [comment]
Its no updated yet in web store.
After updating selector code, app didnt work at all!
What i do wrong?

**Comment by Chesteer89** [comment]
> can anybody send screens of how to do this? chartTimeframeFavorite: '#header-toolbar-intervals div[role="radio"]', chartTimeframeActive: '#header-toolbar-intervals div[role="radio"][data-value][aria-checked="true"]', chartTimeframeMenuOrSingle: '#header-toolbar-intervals div[class^="menu"]',

Please check the setup part:
https://github.com/akumidv/tradingview-assistant-chrome-extension#setup

1. [Download the latest zip](https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/heads/main.zip)
2. Go to chrome://extensions and click on the "Developer mode" switch
3. Click on "Load unpacked".
4. Select the folder with the saved repository files

**Comment by kipler1** [comment]
> chartTimeframeFavorite: '#header-toolbar-intervals div[role="radio"]',
>     chartTimeframeActive: '#header-toolbar-intervals div[role="radio"][data-value][aria-checked="true"]',
>     chartTimeframeMenuOrSingle: '#header-toolbar-intervals div[class^="menu"]',



> can anybody send screens of how to do this? chartTimeframeFavorite: '#header-toolbar-intervals div[role="radio"]', chartTimeframeActive: '#header-toolbar-intervals div[role="radio"][data-value][aria-checked="true"]', chartTimeframeMenuOrSingle: '#header-toolbar-intervals div[class^="menu"]',

1. Download the source code. 
2. Open it in an editor 
3. Open the "Selector" file under "content_scripts"
4. replace the old 3 lines with the new 3 lines. If you need help finding the old lines, use "ctr+f"
5. save the file and close everything 
6. go into Chrome extension settings, to enable developer mode, and drag the entire folder with your edited script into the browser.
7. it should be added to your extension then and you can now use it again
