### ISSUE TITLE
Error: There is not timeframe element on page... Bug not fixed! In web store still old version 2.6. How to update selectors? Thank you!

### ISSUE THREAD

**Issue by AlexProMoney** [akumidv/tradingview-assistant-chrome-extension#136]
![247117728-f44a9b70-b3cc-4bc4-9098-8dc2a1e21191](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/137293270/6901c66e-2816-4ce1-a4c2-57ccdae03ba9)

**Comment by akumidv** [comment]
Fixed, v2.8 in repository. I'll send it to webstore as it would be possible

**Comment by AlexProMoney** [comment]
> Fixed, v2.8 in repository. I'll send it to webstore as it would be possible

Thank You!!!
