### ISSUE TITLE
Abnormal calculation on the deep backtesting

### ISSUE THREAD

**Issue by Bryan3003** [akumidv/tradingview-assistant-chrome-extension#137]
![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/87373515/768e7253-ecf8-40d0-806b-3b88d6988c53)

i found this abnormal behavior when trying to run with Brute force on deep testing, it seems to skip one single step and duplicate the previous result.  The picture above might help on describing it.

However when running brute force without deeptesting it is fine.
![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/87373515/2d68c13f-1588-4dc1-a7fb-d0f11f01a313)

Hope the bug can be fixed, thanks in advance.

**Comment by Bryan3003** [comment]
Deep backtesting with annealing method have the same issue as well

**Comment by VincenzoUrso** [comment]
deep backtesting covers also a bigger time period, are the number of trades the same in your comparison?

**Comment by Bryan3003** [comment]
yes, it is quite obvious as well when it is running deep backtesting (it skipped one step and directly shows the same result from previous step, then keep loading). I might also be quite curious, am i the one who only got this issue?

**Comment by VincenzoUrso** [comment]
I mean, are you sure there is an issue? is the number of trades for those paramenters the same in normal and deep backtesting?

**Comment by Bryan3003** [comment]
yes, i tested couple of times. As i mention above, normal backtest no problem, only it occurs in DEEP backtesting.  Besides, may i know if you often use deep backtesting ?

**Comment by VincenzoUrso** [comment]
I always use it. Have you tried to compare the results by manually changes the values? just to understand if the problem is deep backtesting or the plugin

**Comment by Bryan3003** [comment]
> I always use it. Have you tried to compare the results by manually changes the values? just to understand if the problem is deep backtesting or the plugin

Certainly, it provides different value when changed manually. Have u take a look into the result excel, does it any shown duplicate?

**Comment by SHaaT3k** [comment]
Hi, i saw same problem. In .csv is tons of doubled results and whan i put setting to TV its different. the first with a good result, the second with not so good or bad results

**Comment by akumidv** [comment]
Can you try to increase time between test in options? 
Also in new 2.8.1 version the extension check is button for "Generation report" is clicable (or disabled). Probably in version before - it just not set clickable after changing in parameters - and click for new test just missed and parser grab the previous result.
So please check in new 2.8.1 version that I sent to Google Web-Store today
