### ISSUE TITLE
v2.7 still have Error: There is not timeframe element on page. Open correct page please 

### ISSUE THREAD

**Issue by g001613001** [akumidv/tradingview-assistant-chrome-extension#138]
As the title suggests.
![截圖 2023-06-22 上午5 29 22](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/18544298/007a110b-d270-44c0-bb3e-1e657ec94225)

**Comment by maben1975** [comment]
yes, error again

**Comment by akumidv** [comment]
Fixed, v2.8 in repository. I'll send it to webstore as it would be possible

**Comment by maben1975** [comment]
Great Thx
