### ISSUE TITLE
 "Avg Trade: Long %" shows NaN during cycles.  "Avg Trade: Long %" column not in test file.

### ISSUE THREAD

**Issue by GitHub1m** [akumidv/tradingview-assistant-chrome-extension#139]
With strategy optimization parameters set to max value of "Avg Trade: Long %", the results are NaN, but the Tradingview strategy tester shows Avg Trade: Long % values. Also, "Avg Trade: Long %" is not in Excel columns. I previously thought this was occurred because "Brute Force" method was selected.

**Comment by akumidv** [comment]
I can't reproduce this error. Can you bring more information like screenshots or something another one?
The parsed of strategy results is the same for any types of backtesting methods.
Also if strategy do not have longs for this part of parameter hyperspace  (for brute force method parameters  changed slowly and it can be the same part without longs trades) - this fields can be empty.
