### ISSUE TITLE
are  you able to import data from test result csv?

### ISSUE THREAD

**Issue by VincenzoUrso** [akumidv/tradingview-assistant-chrome-extension#140]
when I try to import data from the test result's csv i have this error

![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/22374826/f7d7bd53-693c-4dc2-aefa-199a35e33721)

**Comment by akumidv** [comment]
You need to use not the test parameters result file, but file with saved strategy parameters. The next button to load parameters.
![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/12490281/a3f379ae-ff0b-4f95-88d1-92a63181948e)

**Comment by VincenzoUrso** [comment]
yes but being able to import the first row of the result after selecting that (as was done by other extension) would be very useful.
I'll put it here as a feature request.
thanks
