### ISSUE TITLE
assistant second instance

### ISSUE THREAD

**Issue by VincenzoUrso** [akumidv/tradingview-assistant-chrome-extension#142]
anyone can tell me what i need to change into the code to have a second instance of the assistant running on my browser?

**Comment by akumidv** [comment]
You can run two different browsers or one of them in incognito mode. 
You also need premium account to have possibility to run two tv accounts in the same time.
But this is not recommended - you possible will have bun by Tradingview for suspicion behavior.
So for this situation more clever to use two different accounts and run them on different servers with different ip.
