### ISSUE TITLE
Deep backtesting doesnt wait for result

### ISSUE THREAD

**Issue by SHaaT3k** [akumidv/tradingview-assistant-chrome-extension#143]
Hi, I have a problem with deep backtesting, every time it starts, only the first setting is calculated and the next one is skipped - it does not wait for the result from the TV, any ideas?

**Comment by VincenzoUrso** [comment]
If you check the csv results, you can see that all the values are calculated

**Comment by SHaaT3k** [comment]
I tested only 100 combinations ... in Attention! popup is "The search is performed among 0 possible combinations of parameters" , but cycles is , for example : 100/20000 , in cvs are calculated value , but not result from TV

**Comment by g001613001** [comment]
> 我只測試了 100 種組合......注意！彈出窗口是“在 0 個可能的參數組合中執行搜索”，但周期是，例如：100/20000，在 cvs 中是計算值，但不是來自 TV 的結果

I have found the same bug as you, and I have also posted another thread, hoping to fix this bug.

**Comment by VincenzoUrso** [comment]
try changing "The maximum waiting time for data of the strategy, if the results table has not been updated (2 times more if used for deep backtesting)."

**Comment by SHaaT3k** [comment]
> try changing "The maximum waiting time for data of the strategy, if the results table has not been updated (2 times more if used for deep backtesting)."

It works, thank you.
I finaly set Delay to 1.25 and maximum waiting to 60 and it seems to be good like before

**Comment by g001613001** [comment]
> > 嘗試更改“如果結果表尚未更新，則策略數據的最大等待時間（如果用於深度回測則為 2 倍）”。
> 
> 它有效，謝謝。 我最終將延遲設置為 1.25，最大等待時間設置為 60，看起來和以前一樣不錯

This setting did not work for me. I have set other different higher seconds, but the problem still exists.

**Comment by VincenzoUrso** [comment]
try this
CTRL +I on your browser, open inspector tool
right click on the reload page button on top-->empty cache and reload

**Comment by akumidv** [comment]
The default value of waiting for strategy results is increased to 45 second (for deep backtesting this period increased x2). But for some strategies this period can be not enough, so before run backtest - measure duration of your strategy calculation and then set this value in options

![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/12490281/c321666d-2e43-4ba1-9bb4-d029e8db7991)
