### ISSUE TITLE
In v2.8, there's a bug in deep backtesting. After adjusting the parameters, the button is not pressed, resulting in abnormal data received

### ISSUE THREAD

**Issue by g001613001** [akumidv/tradingview-assistant-chrome-extension#144]
In v2.8, there is a bug in deep backtesting. After adjusting the parameters, the button is not pressed, resulting in abnormal data received. Currently, when deep backtesting is initiated and the first piece of data is received, the next parameter will be adjusted. However, at this time, the button is not pressed, so the data for this parameter is not received, and it will be dazed for a while. The data for the next parameter will not be pressed until it jumps to the next parameter, and then after adjusting the next parameter, the button is not pressed again. For example, in deep testing of 1000 parameters, the data obtained for 500 parameters will be the same as the data obtained for the previous parameter. 
Link to the bug demonstration video:
https://youtube.com/shorts/WaztSd74yKw

**Comment by akumidv** [comment]
The extension click on the button. but probably it is not clickable in that moment for some reasons.
I recheck current behavior, if non of strategy parameters changed - the deep backtest "Generate report" button is disabled, so not clickable.
In new 2.8.1 version added changed:
- waiting for 5 sec that "Generate report" button clickable, if so clicking for next test
- checking for disabled "Generate report" button - if it disabled, then current set of parameters will be skipped
The version I sent to publish in Google Web-store it also can be downloaded from repository and install to browser manually. 
Can you check current behavior, is it work for you?

**Comment by g001613001** [comment]
> 

That's great, the bug has been successfully resolved!
Thank you.

**Comment by g001613001** [comment]
There is one remaining issue with the deep backtesting button not being clickable. I have asked the official TradingView, and they said it is a problem with their backend and is still being fixed.

**Comment by g001613001** [comment]
> 



> 擴展程序單擊按鈕。但由於某些原因，它那一刻可能無法點擊。 如果策略參數沒有更改，我會重新檢查當前行為 - 深度回測“生成報告”按鈕被取消，因此不可單擊。 在新的 2.8.1 版本中添加了更改：
> 
> * 等待5秒，“生成報告”按鈕可點擊，如果可以點擊進行下一個測試
> * 檢查是否取消了“生成報告”按鈕 - 如果取消，則將跳過當前的參數集
>   我發送到在 Google Web 商店中發布的版本也可以從存儲庫下載並手動安裝到瀏覽器。
>   您可以檢查當前的它對你有用嗎？

This bug has been fixed by the official, and they said that there will no longer be a problem where the button to generate a report is not clickable after adjusting parameters.
