### ISSUE TITLE
Empty timeframes list after correction values: null

### ISSUE THREAD

**Issue by RuiSiang** [akumidv/tradingview-assistant-chrome-extension#145]
I'm getting an error since about two hours ago. Seems tradingview has made some changes to their code.

![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/49300088/1fd64d82-0624-4bec-b66c-27e2f489e495)

**Comment by RuiSiang** [comment]
I'm running the extension on Windows 10, Chrome 114.0.5735.199 on the exact same parameters as a previous successful test. Issue started appearing approximately 3:00 GMT+0

**Comment by akumidv** [comment]
Probably you do not set any values to timeframes field, but turn on the backtesting for timeframes
![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/12490281/a9f4ea49-5a9e-41c0-86db-c4c2f3a8fe92)

**Comment by RuiSiang** [comment]
Sorry my bad
