### ISSUE TITLE
TypeError: Cannot convert undefined or null to object - v.2.81

### ISSUE THREAD

**Issue by VincenzoUrso** [akumidv/tradingview-assistant-chrome-extension#146]
error as in the object trying to launch deep backtesting 

backtest.js:162 Default "Net Profit: All" equal current: undefined
backtest.js:183 For init "Net Profit: All": null
action.js:127  TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at optSequentialIteration (backtest.js:610:10)
    at backtest.testStrategy (backtest.js:62:24)
    at async action.testStrategy (action.js:120:23)
    at async controller.js:50:13
action.testStrategy @ action.js:127

no errors on normal backtesting
tested on two different browsers

**Comment by akumidv** [comment]
From your description the extension didn't found record with Net Profit: All in backtesting results. 
The problems there can be in strategy or in TV language. 
First of all - try to increase the maximum waiting time in "Options & Tools". Probably your strategy didn't finish at the time when waiting limits for strategy results is end and extension trying to parse results.
The second - screenshot with chart and error will be helpfull.
