### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Witcher8** [akumidv/tradingview-assistant-chrome-extension#152]
There is not strategy performance summary tab on the page. - Optimizer shows this error when trying to run on latest version of Scalper Bot V3

**Comment by Witcher8** [comment]
There is not strategy performance summary tab on the page. - Optimizer shows this error when trying to run on latest version of Scalper Bot V3

**Comment by stefantabakovq** [comment]
#151

**Comment by MrDenfish** [comment]
Loaded 2.9.1 as per the recommended manual method. Direct link for this version is here https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/tags/v2.9.1.zip

Uninstall the old version, reinstall, and make certain to close your browser, then restart your browser.  Can confirm 2.9.1 is working.

**Comment by akumidv** [comment]
@Witcher8  Check your's extension version in `chrome://extensions/` if it no 2.9.1 please reinstall. The new version is published in google webstore few days ago.
