### ISSUE TITLE
True/False Inputs are Grey And I Cannot Change

### ISSUE THREAD

**Issue by GitHub1m** [akumidv/tradingview-assistant-chrome-extension#155]
![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/136952717/bf5f214c-695f-445a-94a7-ec05a416caed)

**Comment by orlagwon** [comment]
Damn, man

**Comment by akumidv** [comment]
But what do you want to change there? Boolean values have only two postion: true or false.There is nothing to change, so they inactive.
But you can activate them or turn of by checkbox.

**Comment by GitHub1m** [comment]
> But what do you want to change there? Boolean values have only two position: true or false.There is nothing to change, so they inactive. But you can activate them or turn of by checkbox.

Oh, I thought because the box was grey, the extension wouldn't test both true and false. With the checkbox selected, it works and tests both true and false. Thank you!
