### ISSUE TITLE
Started just now: long "Get the initial parameters" and an error after

### ISSUE THREAD

**Issue by orlagwon** [akumidv/tradingview-assistant-chrome-extension#166]

**Comment by scheerd** [comment]
I was able to get things going again by closing and reopening my browser and reloading my strategy().

**Comment by orlagwon** [comment]
> I was able to get things going again by closing and reopening my browser and reloading my strategy().

Not working for me.

**Comment by akumidv** [comment]
Solved #168 you can wait updates version in your browser after publication new 2.9.3 version in Google Webstore or download and install manually latest version from repository.

**Comment by akumidv** [comment]
The new version of extension published in webstore.
