### ISSUE TITLE
Error: The strategy report did not found. Please retry. If the problem reproduced then it is possible that TV UI changed.

### ISSUE THREAD

**Issue by g001613001** [akumidv/tradingview-assistant-chrome-extension#167]
![error](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/18544298/65377727-9a3e-4db6-addb-fa78ab5f008d)

**Comment by scheerd** [comment]
I was able to get things going again by closing and reopening my browser and reloading my strategy().

**Comment by g001613001** [comment]
I have already tried restarting the browser and rebooting my computer, but I still get this error.

**Comment by VREY8989** [comment]
same here, error. TV change UI for sure

**Comment by tzutoo** [comment]
I have the same error. It was fine yesterday.

**Comment by g001613001** [comment]
[tradingview-assistant-chrome-extension-2.9.2.zip](https://github.com/akumidv/tradingview-assistant-chrome-extension/files/15092303/tradingview-assistant-chrome-extension-2.9.2.zip)

**Comment by GithubJaimeLee** [comment]
https://chromewebstore.google.com/detail/newhorizon-optimizer/icjbokeihkhdilfokigedgpoifnagkjo       👈🏻this one works！

**Comment by akumidv** [comment]
The new version of extension that solve this error published in webstore.
