### ISSUE TITLE
Deep History beta feature of TV completely broke the extension, can't find the strategies

### ISSUE THREAD

**Issue by 4while** [akumidv/tradingview-assistant-chrome-extension#17]
The new feature that TradingView rolled out of Deep History broke the extension that can't find the strategy on chart and reports to load the proper page.

**Comment by akumidv** [comment]
The current changes in UI for user with beta UI for deep history are added to new 1.3 version of extension. It was sent to publish yesterday.
Please wait until new version to be approved. 
While you can install manually from the repository according to the instructions in README.md of the repositry.
If there are any mistakes, I will be grateful for their description.
