### ISSUE TITLE
Settings for strategy after a test completes are not the best

### ISSUE THREAD

**Issue by scheerd** [akumidv/tradingview-assistant-chrome-extension#170]
Until this recent apparent UI change, the strategy settings shown at the end of a test were from the best cycle, and the results matched with the summary UI window reporting the best cycle.  Now the the last cycle settings variation are left in the strategy.  Also one extra cycle is always done; eg if choosing 3 cycles, 4 cycles are done, and the last cycle is different than the others and often is 'error'.  Perhaps the last cycle is meant to reload the settings from the best cycle?

Also not getting the results noted in the csv report if I manually enter the cycle parameter values in the strategy, seems to be a mismatch of offset.  Also noted that the final cycle is still processing when the final results window is reported by TVA, and the last cycle is not reported in the csv.

Yes I can confirm that there is an offset in the csv report, where the results are offset one line down from the parameter settings that yield those results.  

![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/7772050/0ff0e947-da8f-4178-903e-7774e2e57ae9)
![image](https://github.com/akumidv/tradingview-assistant-chrome-extension/assets/7772050/5c89fa6a-b311-47ae-a34e-61142d309499)

**Comment by orlagwon** [comment]
I have results offset one column to the right

**Comment by scheerd** [comment]
Also noting that while the cycles are processing, the results after a cycle settings appear on the TV Performance Summary are not the results shown on the TVA cycle UI, the TVA cycle UI show the results of the previous cycle.

 I increased the delay time and the waiting time significantly, and also cleared all data, and the problem persists.

**Comment by akumidv** [comment]
can you recheck it on new 2.9.3 version - the UI for report table was changed and extension is not work at all, so I can't understand how it parse results for you. Are you sure you are using Trading view assistant?

**Comment by scheerd** [comment]
> can you recheck it on new 2.9.3 version - the UI for report table was changed and extension is not work at all, so I can't understand how it parse results for you. Are you sure you are using Trading view assistant?

Perfect, everything works now, thanks for the quick response!

**Comment by scheerd** [comment]
2.9.3 fixes misalignment of results and includes the interrim fix for #168
