### ISSUE TITLE
Ability to display the optimization results in a sortable table directly in the extension window

### ISSUE THREAD

**Issue by pegaltier** [akumidv/tradingview-assistant-chrome-extension#173]
Currently after an optimization I need to download the csv file and switch to another tool like excel but I find that this is annoying especially that in excel i need to configure many things before the file is usable.

I think it could be very useful to have the ability to display the optimization results in a sortable table directly in the extension so the user don't need to switch to another tool

With a sortable table the user could directly check the most important columns results like drawdown and net profit

**Comment by pegaltier** [comment]
Progress: https://github.com/akumidv/tradingview-assistant-chrome-extension/pull/175

**Comment by akumidv** [comment]
Your PR with this changes was approved and included in current version.
Task closed.
