### ISSUE TITLE
Import/Export icons do not appear on settings panels

### ISSUE THREAD

**Issue by scheerd** [akumidv/tradingview-assistant-chrome-extension#183]
Issue is on both Brave and Chrome browsers.  Test Strategy still loads settings, but the icons no longer appear.

**Comment by alorbach** [comment]
Same Problem, tradingview changed something :/

**Comment by orlagwon** [comment]
Same

**Comment by scheerd** [comment]
Anybody have a workaround?  This is one of the most important features for my workflow.

**Comment by MichalGrzegorzak** [comment]
This should be closed?
