### ISSUE TITLE
Import/Export icons do not appear on settings panels - 2.10.0

### ISSUE THREAD

**Issue by MichalGrzegorzak** [akumidv/tradingview-assistant-chrome-extension#186]
Chrome browser, v2.10.0, started today 22/07/2024. TV again changed something in HTML structure. Could you add current HTML structure to source code, so it would be easier to check what exactly was changed in future?

**Comment by MichalGrzegorzak** [comment]
Hmm, I thought it was not there before, just noticed when I download 'Properties' export from TV, it contains all the strategy parameters. Did they added it? Still I'm guessing you would probably want to re-use your Import/Export functionality and not be dependent on TV for this.

**Comment by akumidv** [comment]
ok I'll check

**Comment by akumidv** [comment]
Sorry still not reproduced. Please add brief description. For example open developer console (F12), then tab `Elements` and button `Select an element in the page to inspect` (or ctrl + shift + c) then click in elements near the button with settings (Default), in console will be showed html code for that element. Screenshot will help a lot.
