### ISSUE TITLE
The backtesting time periods automatically skip 10h, 11h, and 12h. Is this a bug?

### ISSUE THREAD

**Issue by g001613001** [akumidv/tradingview-assistant-chrome-extension#188]
I selected "Backtesting the strategy on timeframes (divided by comma)," but found that 10h, 11h, and 12h are all skipped and it goes directly to 1D.
Is this a bug?
![截圖 2024-08-07 中午12 19 09](https://github.com/user-attachments/assets/61abe61a-5287-452d-80e0-601f54e59905)

**Comment by akumidv** [comment]
Yes it's a bug. All values for hours more than 9h ignored due regexp patterns. I've fixed them. The fix will be in new published version (on next week).
For now you can install extension with fixes manually from repository (description in readme)
