### ISSUE TITLE
Deep backtesting always shows undefined

### ISSUE THREAD

**Issue by xuyamu** [akumidv/tradingview-assistant-chrome-extension#192]
![tva1](https://github.com/user-attachments/assets/cf65dbca-be52-472d-abd9-c6175b36f4a5)

What's going on? This prevents Deep backtesting from running correctly.

**Comment by xuyamu** [comment]
It seems that the calculation time is too long. I changed the strategy to be simpler and it works again.
![tva2](https://github.com/user-attachments/assets/df88bb4a-4250-4935-90a2-dc2fb54e6689)

Changing the delay time also seems to help.

**Comment by akumidv** [comment]
Probably it fixed in version 2.10.1? There are was some changes in TV UI for deep backtest.
