### ISSUE TITLE
Не идет расчет стратегии

### ISSUE THREAD

**Issue by P-5-P-5** [akumidv/tradingview-assistant-chrome-extension#2]
При загрузке файла не идет расчет стратегии
![image](https://user-images.githubusercontent.com/95095530/143608761-91019d1a-90cb-493b-a18e-7d3258b3a124.png)
Сам файл
![image](https://user-images.githubusercontent.com/95095530/143608933-a7038b40-1e44-40fa-ad12-890e89c3b5fb.png)

**Comment by akumidv** [comment]
Посмотрю после выходных. Я не проверял на отрицательных параметрах. Если можете посмотрите еще ошибку в коносли. Для этого нужно нажать F12 и выбрать вкладку console. Там возможно будет сообщение красным, его можно разверунть. Был бы не плох скриншот.

**Comment by P-5-P-5** [comment]
![image](https://user-images.githubusercontent.com/95095530/143673864-21a477a6-0021-44fb-be02-2e008886b8e7.png)
еще заметил, что если стоит 2-3 стратегии, даже отключенные, и они меняются, то тест пробует делать только по одной последней. Те в ТВ я пеключаю их, но тестер на это реакции не дает. Только если я их удаляю с ТВ и оставляю одну, тогда пытается по ней

**Comment by akumidv** [comment]
У вас русский язык стоял в интерфейсе. Русский язык не поддерживается - т.к. 1h таймфрейм показывается как 1Ч. В новой версии 1.1 отправленной на публикацию выдается предупреждение об этом. Английская версия доступна https:///en.tradingview.com
