### ISSUE TITLE
result is wrong!!!

### ISSUE THREAD

**Issue by Ayahuasca94** [akumidv/tradingview-assistant-chrome-extension#21]
Hello, even though the net profit is negative, it takes it numerically and affects the results negatively.

**Comment by akumidv** [comment]
> Hello, even though the net profit is negative, it takes it numerically and affects the results negatively.

Hello, can you attach screenshot how the tradingview backtesting performance show the negative results in your browser when the extension works? TV have at least  2 UI version for now. I checked for current version and for beta version - all were working. But there can be problems of course.

**Comment by akumidv** [comment]
I've added additional check for negative values when the backend performance parsed. Changes pushed to the in repository. Can you install extension manually as it described in the repository README and check?

**Comment by jonathanhyunsung** [comment]
Hello, 

Please find attached:
- Screenshot of negative values displaying as positive
- Screenshot of a CSV from another backtest for "Best Net Profit" next to a smaller sample of the same showing the values
- Screenshot of both CSVs by over and under 0

I will also install the extension manually from the README and help with more information with further testing. Thank you for your hard work.

![Git](https://user-images.githubusercontent.com/67112255/168468644-0aeb9b6d-608d-4696-a606-41bed566bef9.JPG)
![Excel 1](https://user-images.githubusercontent.com/67112255/168468764-8fa1e9a5-0f55-4110-befc-b8241710bef2.JPG)
![Excel 2](https://user-images.githubusercontent.com/67112255/168468769-9005f6a9-abe3-43ce-af44-6ae7c0c721d3.JPG)

**Comment by Ayahuasca94** [comment]
I can't check because I'm getting nan error right now. No matter what I did, I couldn't get past this error.

**Comment by akumidv** [comment]
Can you last load version from repository 1.6 I fixed all problems with negative values and current TV UI changes
