### ISSUE TITLE
Annealing does not work

### ISSUE THREAD

**Issue by DriesVR1232** [akumidv/tradingview-assistant-chrome-extension#22]
When you choose the option of Annealing in the optimizer it gives no data whatsoever. I can see in the strategy tab that it gives the correct % numbers but not in the optimizer screen. I thought it was just a visual bug but when the excel is downloaded it also shows that there was no data collected.
![annealing problem](https://user-images.githubusercontent.com/32335909/168589557-91ebab1a-aedf-455f-af7b-723bd25c47f8.png)
![annealing problem2](https://user-images.githubusercontent.com/32335909/168589562-19aa4fb0-5a15-4206-bd8e-4dc774c2b17a.png)

**Comment by jonathanhyunsung** [comment]
Hello,

I have a couple ideas for troubleshooting as I had this exact issue in the past but don't remember the exact solution:

![TVA Debug](https://user-images.githubusercontent.com/67112255/168640762-61ffa22c-8e8a-4c5f-9b88-c709c35e6fd5.JPG)
- In your upload file under the "step" column, try to keep positive values. If negative values are needed in the parameters, they can be structured as in the screenshot.

- Try to optimize without the additional filters on, it should work fine in sequential but might crash when performing the annealing method.

Hope that helps.

**Comment by kokoulin** [comment]
all variants don't work

**Comment by DriesVR1232** [comment]
> Fix selector path in this file, in 32 and 33 rows https://github.com/akumidv/tradingview-assistant-chrome-extension/blob/main/content_scripts/selector.js
> 
> ```js
> strategyReportRow: '#bottom-area div.backtesting-content-wrapper .ka-table tbody > tr',
> strategyListOptions: 'div[role="listbox"] div[data-name="menu-inner"] div[role="option"] div[class^="label-"]',
> ```
> 
> new class name for backtest table is `.ka-table`

This does not make a difference unfortunately. i still get NaN after changing this

**Comment by akumidv** [comment]
Thank you for your issue. I fix this error in 1.4 version. It was published on weekend, but for now still on checking in store. Can you check after the extension will be updated?

**Comment by akumidv** [comment]
Until this you can use fixed version by install extension in developer mode. The instruction in repository README file

**Comment by DriesVR1232** [comment]
> Until this you can use fixed version by install extension in developer mode. The instruction in repository README file

This does not work unfortunately. I still get the same NaN.

**Comment by akumidv** [comment]
Version published two hours ago, Can you reload your browser. Or remove extension, add it again. Check please that version on the extensions page is 1.4. Then reload tradingview page, it is mandatory. And try.

**Comment by DriesVR1232** [comment]
> 

Still does not work unfortunately

**Comment by DrDenizblc** [comment]
Unfortunately the error persists. I downloaded the package and installed Chrome manually, nothing changed and it seems to be version 1.3 for me.

**Comment by akumidv** [comment]
The last extension version is 1.4. Do you use beta version UI with deep history?

**Comment by akumidv** [comment]
All fixed in version 1.6 (current in repository and I will sent it to Google Store after current 1.5 will be published)
