### ISSUE TITLE
NaN Error

### ISSUE THREAD

**Issue by agentollie** [akumidv/tradingview-assistant-chrome-extension#23]
<img width="413" alt="Screen Shot 2022-05-17 at 10 27 41 am" src="https://user-images.githubusercontent.com/105684807/168703594-04f427b5-7927-427b-8168-41e6990318c2.png">
Working yesterday - Not working today...
Get this weird NaN error?
Thanks

**Comment by Steadyeye3** [comment]
same here. test runs but csv thats generated after the test has no data

**Comment by akumidv** [comment]
Thank you for your issue. I fix this error in 1.4 version. It was published on weekend, but for now still on checking in store. Can you check after the extension will be updated?

**Comment by akumidv** [comment]
Until update you can use fixed version by install extension in developer mode. The instruction in repository README file

**Comment by Steadyeye3** [comment]
yes, still happening in the fixed version, ID: afgffeoiimejhoekaeimhcaadcidlogb

**Comment by akumidv** [comment]
This ID is id of extension not the version. Version published two hours ago, Can you reload your browser. Or remove extension, add it again. Check please that version on the extensions page is 1.4. Then reload tradingview page, it is mandatory. And try.

**Comment by DriesVR1232** [comment]
> 
I tried and it gives the same result unfortunately. NaN in the popup screen to follow the progression of the test and the message "There is no data for conversion" in the excel file.

**Comment by jonathanhyunsung** [comment]
Both versions, 1.3 and 1.4, produce the same CSV error.

As OP mentioned- was working fine yesterday

**Comment by 4while** [comment]
Version - 1.4 / Size 3.7 MB
brings NaN as some guys said before
Used Profit Factor All (annealing or brute) has the same effect
I'm using the new UI with the deep history slider

**Comment by ogerik** [comment]
Same issue here, on the older version its working but on the versions which is installed yesterday and today (brand new installation) has the same issues.

**Comment by akumidv** [comment]
Unfortunately, I don't have access to the beta version and I can't test on it. On the regular version, I can't reproduce this error.

**Comment by 4while** [comment]
> Unfortunately, I don't have access to the beta version and I can't test on it. On the regular version, I can't reproduce this error.

Open a support ticket and ask for beta testing enrollment, i don't know who's eligible and who is not, they did it for me in 1 hour.

**Comment by ogerik** [comment]
You mean the beta version of Chrome? You think this could be the problem?

**Comment by Steadyeye3** [comment]
Same issue on 1.4 update. NaN while optimizing and "There is no data for conversion" is the only thing is the results .csv file

**Comment by Steadyeye3** [comment]
was not using the deep data beta for my testing

**Comment by jonathanhyunsung** [comment]
> was not using the deep data beta for my testing

Same

**Comment by 4while** [comment]
I start to think there are three versions of UI
The old one, the new one without the deep history slider and the ones with the slider

**Comment by 4while** [comment]
I don't think there are "both" aka two versions because if akumidv said he sees no problem but i (with the deep history slider) and a friend of mine (without the deep history slider) can't pass the NaN error.

**Comment by akumidv** [comment]
> > Unfortunately, I don't have access to the beta version and I can't test on it. On the regular version, I can't reproduce this error.
> 
> Open a support ticket and ask for beta testing enrollment (for deep history), i don't know who's eligible and who is not, they did it for me in 1 hour.

Yes, I did the same, but have got decline

**Comment by akumidv** [comment]
Colleagues, I have corrected the error. All the fixes are in the repository, you can install and check. I sent the new version 1.5 to the publication in Google Store
The reason for the error is in two dimensions - now the backtesting data is hidden in the TV API, at least I didn't find them quickly. And the html selectors of the backtesting results table were changed too. I.e. both the main and reserve method to get data were broken.
Please try it, if the error repeats - write here please. If you can take a screenshot of the entire screen with the console open (F12, console tab)

**Comment by DriesVR1232** [comment]
Still same issue.
![extension problem](https://user-images.githubusercontent.com/32335909/169236514-35673428-9259-497f-9c0f-0555c8955856.png)

Seems like the values are not given to the variables at line 142 and 165.

**Comment by jonathanhyunsung** [comment]
> Still same issue. ![extension problem](https://user-images.githubusercontent.com/32335909/169236514-35673428-9259-497f-9c0f-0555c8955856.png)
> 
> Seems like the values are not given to the variables at line 142 and 165.

With appreciation to the Author's hard work - 
Getting the same NaN error and CSV, the F12 console shows the same logs about lines 142 and 165 from the version 1.5 manual installation.

**Comment by akumidv** [comment]
> Seems like the values are not given to the variables at line 142 and 165.

Are you sure that you use 1.5 version? Because in new version when the extension do not get table selectors it show an error about this and do not process backtesting optimization. In chrome version are not updated, it demand 2-3 days. You can test only if install extension from repository in developer mode.

**Comment by akumidv** [comment]
![image](https://user-images.githubusercontent.com/12490281/169432017-240fdaea-deed-424d-b0c4-06ea57d92ed2.png)
Example

**Comment by DrDenizblc** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/105722707/169435602-9b9cdc7e-4438-4582-8e03-3c2e8d894ef5.png)

i am getting an error like this

**Comment by jonathanhyunsung** [comment]
![Untitled](https://user-images.githubusercontent.com/67112255/169437743-93396706-2316-4fed-95a2-61d5856c44c4.png)

Hello,

For 1.5, Best "Net Profit: All" works but negative values display as positive values like in the other thread. Best "Net Profit: %" produces the NaN error.

**Comment by DrDenizblc** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/105722707/169438228-27f542d8-86bb-4dae-852b-87f93e80d639.png)
**I installed the extension from the repository.
I restarted chrome.
Then I had the parameters analyzed and separated the unnecessary parameters.
I restored the parameters to version 1.5.
Then I ran it but I got an error like this NAN
can you guys tell me where i made a mistake?
I appreciate your work...**

**Comment by micant** [comment]
@akumidv 
Tested by installing manually in developer mode - can confirm is working again for v1.5 and Chrome v101.0.4951.64.
Thank you for your hard work on this excellent plugin.

**Comment by Ayahuasca94** [comment]
> @akumidv 
> 
> Tested by installing manually in developer mode - can confirm is working again for v1.5 and Chrome v101.0.4951.64.
> 
> Thank you for your hard work on this excellent plugin.
> 
> 

I say negative results

**Comment by akumidv** [comment]
> 

This is another error. I'll check it today evening what that can be

**Comment by akumidv** [comment]
> ![Untitled](https://user-images.githubusercontent.com/67112255/169444002-794daff5-570f-498a-b82b-d0265d14594d.png) ![Untitled2](https://user-images.githubusercontent.com/67112255/169444014-128c074c-a938-433c-be0d-8183a1b459c1.JPG)
> 
> Hello,
> 
> For 1.5:
> 
>     1. Best "Net Profit: All" Annealing works but negative values display as absolute values like in the other thread.
>        -> Best "Net Profit: All" Annealing is optimizing based on absolute values, both negative and positive.
>        -> After everything runs, the "Best 'Net Profit: All': 7139" in the screenshot shows as "Best 'Net Profit: All': -7139" in the Performance Summary tab, it's a negative value and should be picked up by the extension as a negative value instead of positive.
> 
>     2. Best "Net Profit: All %" Annealing produces the NaN error. Using % Annealing was the workaround to Problem (1.) when it was working a few days ago, but it's been making the NaN error since.

Thanks. This is an another problem. And as I see it is not from current version of TV assistants, May be from another fork of this extension (The optimizer maybe?). For now It doesn't have function `getStrategyTemplate`
May be you use both? Then you need for disable another version of extension they can confuse.

**Comment by akumidv** [comment]
> **I installed the extension from the repository. I restarted chrome. Then I had the parameters analyzed and separated the unnecessary parameters. I restored the parameters to version 1.5. Then I ran it but I got an error like this NAN can you guys tell me where i made a mistake? I appreciate your work...**

Thanks. This is an another problem. And as I see it is not from current version of TV assistants, May be from another fork of this extension (The optimizer maybe?). For now It doesn't have function getStrategyTemplate
May be you use both? Then you need for disable another version of extension they can confuse.

**Comment by jonathanhyunsung** [comment]
![image](https://user-images.githubusercontent.com/67112255/169448019-9cdcd4d3-dd37-4c68-83ae-0255e5f2c114.png)
![image](https://user-images.githubusercontent.com/67112255/169448085-d27e6ebf-04c8-414c-a7a4-9ef18d3bceee.png)

Are any of the above the cause of the absolute values? I've disabled/removed all TV Assistants except TV Assistant 1.5, the screenshots are from the backtest.js of 1.5.

**Comment by akumidv** [comment]
> ![image](https://user-images.githubusercontent.com/67112255/169448019-9cdcd4d3-dd37-4c68-83ae-0255e5f2c114.png) ![image](https://user-images.githubusercontent.com/67112255/169448085-d27e6ebf-04c8-414c-a7a4-9ef18d3bceee.png)
> 
> Are any of the above the cause of the absolute values? I've disabled/removed all TV Assistants except TV Assistant 1.5, the screenshots are from the backtest.js of 1.5.

No, This is another part of code. The parser function is `tv.parseReportTable()` and it have two method to detect negative values, so I wondered why both failed.

**Comment by jonathanhyunsung** [comment]
> 

Switching the currency to NZD is making the right optimizations, using Net Profit: All; annealing

**Comment by jonathanhyunsung** [comment]
> > Best "Net Profit: All" Annealing works but negative values display as absolu
> 
> This is another error. The problem is in `$` before digits. I'll fix this today or tomorrow. For now you can change the currency in strategy properties for that ones where currency after digits.
> 
> ![image](https://user-images.githubusercontent.com/12490281/169447710-dfdab3eb-a9f5-48e6-8ef5-e2f12b7bbdd8.png)

Switching the currency to NZD is making the right optimizations, using Net Profit: All; annealing

**Comment by akumidv** [comment]
> > > Best "Net Profit: All" Annealing works but negative values display as absolu
> > 
> > 
> > This is another error. The problem is in `$` before digits. I'll fix this today or tomorrow. For now you can change the currency in strategy properties for that ones where currency after digits.
> 
> Switching the currency to NZD is making the right optimizations, using Net Profit: All; annealing. Thank you again.

I fixed parsing values with currency. So it can correct parse values like `-$100`. Can you check. It seems working now. Changes in repository as version 1.6.

**Comment by akumidv** [comment]
Example 
![image](https://user-images.githubusercontent.com/12490281/169452622-e99f76e6-e697-4bcd-837f-d5260881cb33.png)

**Comment by jonathanhyunsung** [comment]
It's working perfectly for Default Currency, Net Profit: All, Annealing.

Thank you, very grateful for your awesome work.

**Comment by akumidv** [comment]
> It's working perfectly for Default Currency, Net Profit: All, Annealing.
> 
> Thank you, very grateful for your awesome work.

Update please again. I fix some problem with names of max drawdown and parse data for %

**Comment by jonathanhyunsung** [comment]
The % makes NaN but the regular "Net Profit: All" works perfectly. The % was only a workaround/alternative because of the negative value issue in "Net Profit: All" (which was connected to the currencies).

**Comment by DriesVR1232** [comment]
The "Net Profit: All" works fine
![extension problem2](https://user-images.githubusercontent.com/32335909/169478647-b1a232bd-6998-46c7-a0df-631961787a29.png)

the "Net Profit:All%" doesnt. there i still get the NaN error.
![extension problem3](https://user-images.githubusercontent.com/32335909/169478672-665105e7-bbe2-4128-91b0-82cfe7147dff.png)

**Comment by akumidv** [comment]
I'll check tomorrow again. For me now it works on new 1.6 version.
![image](https://user-images.githubusercontent.com/12490281/169527095-179f6db1-75b8-41cc-b15e-61062233aacb.png)

**Comment by 4while** [comment]
I see a different graph of profit - drawdown.
Do they attempt to redraw again the area ?
The xpath to the strategy tab and performance summary link don't look the same

**Comment by JasonSPH** [comment]
The "Net Profit: All" works fine for me too, but the "Sharpe Ratio: All" still not working...

**Comment by DrDenizblc** [comment]
With version 1.6, I ran a scan for very long hours. Without using % as currency NZD. It saved the best setting out of 5000 scans and did not show it to me. The values it saved are wrong.
 I got another error, when I run the extension, after get the best parameters. it didn't update the strategy, losing all the parameters got . I hope you fix it, becaouse is amazing extension. thank you so much for all you work.

**Comment by 4while** [comment]
@akumidv : Instread of focusing on XPATHs and DIVs and such, why don't you focus on file manipulation of the strategy details?
You will gain time from future cosmetic upgrades of the javascript code and even if they change the details in the csv, is just a different set in the field array, another comma and done.
Maybe few MBytes extra at the cache or non real time results but what matters is robustness and overall performance.

**Comment by akumidv** [comment]
> @akumidv : Instead on focusing on XPATHs and DIVs and such, why don't you focus on file manipulation of the strategy details? You will gain time from future cosmetic upgrades of the javascript code and even if they change the details in the csv, is just a different set in the field array, another comma and done. Maybe few MBytes extra at the cache or non real time results but what matters is robustness and overall performance.

@[4while](https://github.com/4while) The extension implements emulation of user actions. I know of no other way to make this work, other than to build a robot that works with the interface. Yes, any change in the interface breaks the work, but usually it won't take long to fix it. As for reliability and performance the most reliable way is to make all calculation by using python. That's exactly what I do for myself and test in the Google/AWS cloud (some simple examples in my current course for local community https://github.com/akumidv/quants-algotrading-khv and there https://github.com/akumidv/startup-khv-ai-study). 

A test of 2-5 seconds per iteration is a very slowly to optimally test a large parameter space. It should be at least 100-1000 times faster. Perhaps I will release it as an application in the future.
