### ISSUE TITLE
There is not strategy name element on page. Open correct page please

### ISSUE THREAD

**Issue by 4while** [akumidv/tradingview-assistant-chrome-extension#25]
Just in, worked ok before 2 hours.
Using the "Deep History" layout.

**Comment by akumidv** [comment]
Thanks. Fixed - the reason on TV UI changes. All fixes in repository (with new strategy parameters space window) - you can download extension in developer mode (instruction in repository readme). Also sent for publishing in Chrome store (~2-3 working days)
