### ISSUE TITLE
No strategy name element on page

### ISSUE THREAD

**Issue by DriesVR1232** [akumidv/tradingview-assistant-chrome-extension#26]
Since a few hours ago i get the error that the extension cannot find the strategy element on the page even though it is visibly open. I think it is because tradingview made some new changes again that the name of the HTML element got changed or something of this sort.
Screenshot with the error and strategy element open:
![strategy problem](https://user-images.githubusercontent.com/32335909/170992476-886289d0-3637-4e59-9f02-f6562d3f3f10.png)

Screenshot with tradingview changes
![strategy problem2](https://user-images.githubusercontent.com/32335909/170992811-945d0659-361c-4586-a10b-00df2530df03.png)
I saved the html code of the page incase that could be useful for you aswell.

**Comment by 4while** [comment]
I opened the #25 for the same reason.
The issue is fresh. Worked before 4 hours without a problem

**Comment by akumidv** [comment]
Thanks colleagues. Fixed - the reason on TV UI changes. All fixes in repository (with new strategy parameters space window) - you can download extension in develop mode. Also sent for publishing in Chrome store (~2-3 working days)

**Comment by DriesVR1232** [comment]
> Thanks colleagues. Fixed - the reason on TV UI changes. All fixes in repository (with new strategy parameters space window) - you can download extension in develop mode. Also sent for publishing in Chrome store (~2-3 working days) Version 1.7

Thank you it works now! However i still have the Nan error for net profit all %.
![extension problem4](https://user-images.githubusercontent.com/32335909/171118823-9f8940ca-7d14-42a7-8077-244f980df3ef.png)

**Comment by akumidv** [comment]
Hmm. I'll check this. Do you have beta TV UI interface with deep history?

**Comment by akumidv** [comment]
I found an error, It is fixed for now. Can you check? Version 1.8 in repo. Also set decimal for preformance trades values.

**Comment by DriesVR1232** [comment]
> Hmm. I'll check this. Do you have beta TV UI interface with deep history?

I have the beta interface yes, i will check your 1.8 version and say if it works in a minute.

**Comment by sub888** [comment]
> > Привет коллега. Никак не воспроизводится тестер. Все это время пишет НАН. Что я делаю неправильно? Спасибо, за великолепно проделанную работу. Ваша программа очень сильно помогает в работе. Может быть это связано с хромом? У меня стоит последняя версия 102.0.5005.63.![Скриншот_5](https://user-images.githubusercontent.com/106596981/171168270-09afbd0f-a052-4054-800e-3386ea6b8dc0.jpg)
> > Ошибка выдает такую![Скриншот_6](https://user-images.githubusercontent.com/106596981/171181567-01669c41-df4c-45f5-a7ba-e15ae8671a89.jpg) ![Скриншот_7](https://user-images.githubusercontent.com/106596981/171181803-1ecf38cb-febe-41a7-b150-a0e024599bf8.jpg)
> 
> Расширение работает только на английской версии, переключитесь на английский, должно помочь. Расширение работает только на английской версии Tradingview, пожалуйста, переключитесь на английский язык.

Вот оно оказывается что). Спасибо огромное за ответ). Теперь все работает! Тестирую)
