### ISSUE TITLE
Get Template and Test strategy don't detect & manage float params

### ISSUE THREAD

**Issue by pulsar14** [akumidv/tradingview-assistant-chrome-extension#29]
"Get Template" functionality doesn't manage float values in the strategy parameters. **Only integer?**

e.g.
```
// @version=5
strategy(...)
i_multi = input.float(  title='Multiplier', defval=3.1, minval=0.1, step=0.1, group="COEFF", tooltip="Hello Folks!")
```

Affter a "_Get Template_", in the Excel I see:

```
Parameter | From | To    | Step | Default | Priority
Multiplier| 3.1  | 19.6  | 1    | 6.8     | 18
```

So, I forced Step value to 0.1 and imported into the addin the csv with the helpful "_Upload parameters_".
When I run "_Test strategy_", the popup list, that I can see before the execution, shows the active Multiplier param with a **step value = 1** and only increments by 1 unit and no 0.1 as expected from the strategy code and from the "_Upload parameters_" command.
Is there something I'm missing or wrong?

Kind Regards

**Comment by akumidv** [comment]
Hi, thanks for your issue. I fixes this error and now extension can set float parameters from parameter window. Also you can click in "Skip&Run"button ( ("Run default" in previous version)  to run without changes in window and run with uploaded (or default) parameters .
I'm planning to send for review and publish new version on Tuesday, you can check it now if install you extension from repository (instruction in repository README.md).

**Comment by pulsar14** [comment]
Thank U thank U thank U very much! Great job. Kind Regards,Stefano   From: Andrei KuminovSent: Monday, June 6, 2022 6:17 AMTo: akumidv/tradingview-assistant-chrome-extensionCc: Stefano.Scalcinati; AuthorSubject: Re: [akumidv/tradingview-assistant-chrome-extension] Get Template and Test strategy don't detect & manage float params (Issue #29) Hi, thanks for your issue. I fixes this error and now extension can set float parameters from parameter window. Also you can click in "Skip&Run"button ( ("Run default" in previous version) to run without changes in window and run with uploaded (or default) parameters .I'm planning to send for review and publish new version on Tuesday, you can check it now if install you extension from repository (instruction in repository README.md).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
