### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by boyxil** [akumidv/tradingview-assistant-chrome-extension#3]
Расширение работает только если tradingview на английском, стоит это указать в описании или решить проблему.
спс.

![Аннотация 2021-12-05 162040](https://user-images.githubusercontent.com/1186206/144750582-f86ed5fe-3173-4678-ad93-5c62ddf98cc3.png)

**Comment by akumidv** [comment]
Все верной, реализация только для английского языка. В новой версии (её можно скачать как архив из репоизтория) выдается предупреждение об этом.
