### ISSUE TITLE
Extension does not use steps lower than 1.

### ISSUE THREAD

**Issue by DriesVR1232** [akumidv/tradingview-assistant-chrome-extension#31]
In the csv file you can specify the step with which the extension will go through the settings, but it does not go below a step of 1 anymore. I will attach a screenshot where it shows i use a 0.1 step for the Stop loss and Take profit but during the tests it only uses steps of 1. It used to work before so i dont know if i did something wrong or if something in the code changed that this isnt posible anymore.  I tried to use both 0.1 and 0,1 and neither work.
![extension problem5](https://user-images.githubusercontent.com/32335909/172042108-129a31b9-4abf-4214-a69a-2fb5318e7db4.png)

**Comment by akumidv** [comment]
Hi, thanks for your issue. I fixes this error and now it can possible to set float parameters. Also you can click in "Skip&Run" button to run without changes in window and run with uploaded (or default) parameters .
I planned send to review and publish new version on Tuesday, you can check  if install extension from repository.
