### ISSUE TITLE
Missing column in CSV

### ISSUE THREAD

**Issue by Lospollos82** [akumidv/tradingview-assistant-chrome-extension#32]
Hello
I wanted to merge several CSV files to make one.
When I converted the files to Excel with the "," separation, I realized that the columns were not the same, depending on the file, some columns were missing.
Is it possible to have files with columns that match? Thanks
![image](https://user-images.githubusercontent.com/106482697/172178381-18988d5f-d3eb-4cc7-9231-89a40ea61570.png)

**Comment by akumidv** [comment]
There are different columns. All column names are parsed from the table shown by the tradingview performance tab. If there are changes in it, then the column names and order also changed.
