### ISSUE TITLE
Error message 

### ISSUE THREAD

**Issue by Lospollos82** [akumidv/tradingview-assistant-chrome-extension#33]
![Screenshot_20220607-152457~2](https://user-images.githubusercontent.com/106482697/172392232-9c59f4d4-fac4-4635-a6c6-d60382e400a1.png)
I got this error message several times today.

**Comment by akumidv** [comment]
Sorry a can't see anything on this screenshot. Only problem that selector of performance tab do not found on page. I've checked right now and all ok. But I do not have beta UI version. Can you click F12 button, then open console tab and take screenshot with full page?

**Comment by Lospollos82** [comment]
![image](https://user-images.githubusercontent.com/106482697/172554090-ff793f08-0432-46d8-ba86-2e569f35a75e.png)

**Comment by Lospollos82** [comment]
![Capture d’écran du 2022-06-09 09-33-55](https://user-images.githubusercontent.com/106482697/172792142-492ca9eb-7012-46e8-b14a-97f33c6a0bcc.png)

**Comment by akumidv** [comment]
Your screenshot shows that everything works for at least 700 cycles, and then stops. At the same time, tradingview errors are also visible. It may be that you minimize the browser window or block it with another app - in this case, chrome stops the execution of scripts on the page, including extensions. And when it restores, an error occurs.
