### ISSUE TITLE
Error message keeps popping up

### ISSUE THREAD

**Issue by Bigbear81** [akumidv/tradingview-assistant-chrome-extension#36]
I keep getting an undefined properies error message. how can i fix this? It happens for th Take profit factor as well as the length.

<img width="960" alt="2022-06-23 08_51_54-Greenshot" src="https://user-images.githubusercontent.com/108073128/175305405-2c235d89-aedf-4656-9b0e-783500072eca.png">
<img width="960" alt="2022-06-23 08_50_02-Greenshot" src="https://user-images.githubusercontent.com/108073128/175305407-64e239e9-1706-4899-a7a5-9aba077f31eb.png">

**Comment by akumidv** [comment]
I'll check it at begin of the next week. It would be helpful the screenshot with developer console open (please press F12 and open  console tab)

**Comment by akumidv** [comment]
How about screenshot with console and please expand string with error.

**Comment by Bigbear81** [comment]
It seems to be working just fine now. May have been something I was/wasnt
doing.
