### ISSUE TITLE
Error message keeps popping up

### ISSUE THREAD

**Issue by thecao365** [akumidv/tradingview-assistant-chrome-extension#37]
The extension keeps giving an error.

![image](https://user-images.githubusercontent.com/4857521/175526181-ffc70148-f404-4882-9eb3-b9ea235e6b53.png)
![image](https://user-images.githubusercontent.com/4857521/175526399-010b93a9-4b6d-4346-a03b-af36af366743.png)

**Comment by Quetzalquatl** [comment]
updated tradingview. I guess that's the reason.... I hope it gets updated soon...

**Comment by Quetzalquatl** [comment]
I have the same problem unfortunately...

**Comment by akumidv** [comment]
I fixed this problem today. You can try by installing extension from repository or waiting when the new version will be reviewed and published in store.

**Comment by thecao365** [comment]
> I fixed this problem today. You can try by installing extension from repository or waiting when the new version will be reviewed and published in store.

Tks akumidv 👍

**Comment by akumidv** [comment]
> 

You can describe features as new issue. I plan to improve the extension, but what ideas to take to work is not an easy question and depends on how much time this new features demand on their implementation.
