### ISSUE TITLE
Error during install of extension

### ISSUE THREAD

**Issue by dmccoyks** [akumidv/tradingview-assistant-chrome-extension#38]
Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist. Error occurs after using load unpacked of chrome extension.

**Comment by akumidv** [comment]
I couldn't reproduce this error, Can you take screenshot when the browser console tab is opened? (Press F12 and open tab console, then reload tradingview page)
The extensions do not have any part of code that use requests.

**Comment by dmccoyks** [comment]
Sure, I haven't tried it for a couple days so let me see if it still shows the error. Thank you
________________________________

**Comment by Ayahuasca94** [comment]
error persists :/

**Comment by akumidv** [comment]
Without screenshot I can't understand what this error is and  where it occurred.
