### ISSUE TITLE
Cannot read properties of undefined with filter-on for Annealing method

### ISSUE THREAD

**Issue by duocyber** [akumidv/tradingview-assistant-chrome-extension#39]
Very good change to have your extension!

I always got error of undefined properties during the backtesting when using filter. It happened to every strategies I tested, though there is no problem without filter (500-1000 iterations).  The backtesting parameters could be run for few combinations (~3-10) before it stopped (both less/more filters).  It seems some parameters value has gone or not updated during the test.

![TV assistant filter error](https://user-images.githubusercontent.com/6591215/177483392-e545dff6-61ce-4c04-bd1c-b09e59452280.png)

![TV assistant filter error 2](https://user-images.githubusercontent.com/6591215/177483435-32018708-9cdb-48e9-b209-88d6c9893b56.png)
.

**Comment by duocyber** [comment]
Further investigation, maybe the problem occurs specific to Annealing Method.  I hope this can be solved, as I like the annealing method -- it could approach to the local optimum quite fast.

**Comment by akumidv** [comment]
Can you take screenshot with console window open in browser developer mode (F12 and tab console). The console contain additional information where this error occured (if you can please expand error stack trace string)

**Comment by akumidv** [comment]
Thanks you. I found this error and fix it, changes in repository. But I haven't included this changes in version 1.11, they will be in version 1.12.
Can you install version from repository and check how it is going now for this method in your browser?

**Comment by duocyber** [comment]
I have tested it briefly on 1.12.  The filter in Annealing Method looks to be good.  There got no error message now.  I am still checking that the filter working as expected.  (Also, the DD now work properly including get template and the uploaded CSV file.)  Thanks so much.

Would be very much appreciated to see the future optimizing algorithm as Genetic Algorithm, etc.  Hope also maybe you can find better way to cope with CSS selection of TV.  As this got to happen from time to time.

**Comment by duocyber** [comment]
Is it possible also to have filter in range?  As GT or LT is only filter @ one side of the parameters while sometimes it should be more appropriate to specify instead in range. Eg. there should be suitable Buy/Sell number of trades not more or less.  If we trade too often it got chances that we will loss accumulated little trades and if we trade too little it got more opportunity to get less accuracy of the indicators.
