### ISSUE TITLE
Use range in filter?

### ISSUE THREAD

**Issue by duocyber** [akumidv/tradingview-assistant-chrome-extension#42]
Is it possible also to have range in filter? As GT or LT is only filter @ one side of the parameters while sometimes it should be more appropriate instead of that to specify in range.

Eg. there should be suitable Buy/Sell number of trades not more or less. If we trade too often it got chances that we will loss in accumulated little trades and if we trade too little it got more unreliable long periods for the indicators' time frame.

We can also use filter to imply second target such as max drawdown. In this case we would to minimize it at the same time I don't want it to be zero as it looks not feasible and proof inaccurate for long run.

**Comment by akumidv** [comment]
It is suggestion to implement second filter. I'll think about this. If you need this one right now, you can use fork of extension where I already implemented this by order - it is named now as `Strategy Helper`, it is also free.

**Comment by duocyber** [comment]
Thanks a lot. I'll check it out.

**Comment by duocyber** [comment]
That's it!
