### ISSUE TITLE
that's not a problem, just thank you

### ISSUE THREAD

**Issue by Quetzalquatl** [akumidv/tradingview-assistant-chrome-extension#43]
Hello master. I'm testing your extension on my own strategy in tradeview and it seems to be successful so far. This week or next week I will be trading in real time. I hope there will be no problem. If there is no problem, I would like to donate some of the money I earned to you. because you made my job easy and you deserve it... and i hope you can improve the extension a bit more... (my english is bad i hope you understand what i wrote)

**Comment by akumidv** [comment]
Thanks for the feedback.

If you have any suggestions, then you can create a issue with description. I collect them and some of them take to work. If you have a task that I don't plan to do yet, you can order it for development by payment.

Donates, I'm not planning yet.
