### ISSUE TITLE
How to take params from external indicator as data source for strategy under test?

### ISSUE THREAD

**Issue by beskrovnykh** [akumidv/tradingview-assistant-chrome-extension#45]
I am looking for possibility to use parameters not from the strategy, but from the indicator, which serves as an external data source for the strategy under test. This is done using https://www.tradingview.com/blog/en/use-an-input-from-another-indicator-with-your-strategy-19584/
Is it difficult to support such feature?

**Comment by akumidv** [comment]
This is not a simple implementation, and it seems quite rare. Most strategies themselves contain indicators and parameters for them.
 I don't see the point in such an improvement yet. You can make it yourself or order it and make a pull request to add to the repository code
