### ISSUE TITLE
clean best results

### ISSUE THREAD

**Issue by Quetzalquatl** [akumidv/tradingview-assistant-chrome-extension#47]
this answer is kind of funny. I already know this button. I don't want everything deleted. I only want the best result values to be deleted. I want to keep the parameter settings.... understand?

**Comment by akumidv** [comment]
![image](https://user-images.githubusercontent.com/12490281/183141631-78cbaebe-94d3-4fb5-9d58-6877ae0a1cab.png)

**Comment by Quetzalquatl** [comment]
this answer is kind of funny. I already know this button. I don't want everything deleted. I only want the best parameter values to be deleted. I want to keep the parameter settings I have set.... do you understand?

**Comment by Quetzalquatl** [comment]
this answer is kind of funny. I already know this button. I don't want everything deleted. I only want the best result values to be deleted. I want to keep the parameter settings.... understand?

**Comment by akumidv** [comment]
Was done in 2.1 version "Options&Tools" tab
