### ISSUE TITLE
Change Tradingview time interval.

### ISSUE THREAD

**Issue by MrDenfish** [akumidv/tradingview-assistant-chrome-extension#48]
Hello again, and thanks for this awesome  extension.  Is it possible to change settings in Tradingview with the extension? Specifically cycle through the starred (favorites) Time Interval. I would like to be able to run through some, but not all time variables when backtesting.
![Untitled](https://user-images.githubusercontent.com/108489215/183518414-89fdda61-1ebd-4e6e-b9a3-aa3b4334e98c.jpg)

**Comment by akumidv** [comment]
This implementation present in "The helper" extension. There you can check strategy parameters in different timeframes. 

About automatically backtesting timeframges - it is additional parameters to parameter space. It would increase backtesting a lot. I don't think it will be useful for many users. 

Also as I know Tradingview now try to detect when users use some automation bots for backtesting. And all functionality that increase backtesting cycles will increase the risks of bun for users.

**Comment by MrDenfish** [comment]
I see, thank you for addressing  my question.

**Comment by akumidv** [comment]
Implemented in version 2.0 as field with list of timeframes and checkbox to process backtesting on all timeframes in list

**Comment by akumidv** [comment]
The 2.1 version with fixes has published in webstore
