### ISSUE TITLE
Tradingview has changed the interface again!

### ISSUE THREAD

**Issue by thecao365** [akumidv/tradingview-assistant-chrome-extension#49]
hi bro @akumidv !

Tradingview has changed the interface again!

![image](https://user-images.githubusercontent.com/4857521/184131834-225d4989-91a6-4c06-8a34-7278159543d7.png)
![image](https://user-images.githubusercontent.com/4857521/184131839-fe0771d1-17f2-4c6f-b9e6-f47479652979.png)
![image](https://user-images.githubusercontent.com/4857521/184132029-a997e7ae-d7ce-41c9-bb15-38decbb8a22e.png)

**Comment by MrDenfish** [comment]
Can confirm

![Screen Shot 2022-08-11 at 8 18 14 AM](https://user-images.githubusercontent.com/108489215/184181702-8db01ac0-bab8-4764-bc58-963487ef4c36.png)
![Screen Shot 2022-08-11 at 8 18 29 AM](https://user-images.githubusercontent.com/108489215/184181689-dd368d86-b91d-46db-adbd-8298989a0fa4.png).

**Comment by DriesVR1232** [comment]
Same here

**Comment by eXcount** [comment]
Same here
![image](https://user-images.githubusercontent.com/111085567/184223229-d16d812f-bfc5-4c18-93bb-cb22ca9a014f.png)

**Comment by chaiyapruekr** [comment]
Same problem

**Comment by stefantabakovq** [comment]
@thecao365 check my proposed patch (crude, but works) in PR

**Comment by akumidv** [comment]
fixed. Today I sent to publish in chrome store
