### ISSUE TITLE
Wrong Cycles number in "Strategy parameters" when the param to be tested starts From 0 [zero]

### ISSUE THREAD

**Issue by pulsar14** [akumidv/tradingview-assistant-chrome-extension#50]
Example:

> float param [from **1** to 3, step 1]   --> Cycles = 3                  **Ok!**
> float param [from **0.1** to 3, step 0.2]   --> Cycles = 15          **Ok!**
> float param [from **0** to 3, step 1]   --> Cycles = 1                  **Wrong!**
> float param [from **0** to 3, step 0.1]   --> Cycles = 1               **Wrong!**

Both integer and float params can't be tested if from is = to 0

**Comment by pulsar14** [comment]
![image](https://user-images.githubusercontent.com/14016570/184188848-dfe6b187-35e8-454b-98ee-b0708c73d51b.png)

**Comment by akumidv** [comment]
Thank you for issue. Fixed. Changes will be in next published version or you can install extension from repository to check.

**Comment by pulsar14** [comment]
Thank U very much!!!!
