### ISSUE TITLE
enhancement:  Add the option to uncheck ALL checkbox in "Strategy parameters" popup

### ISSUE THREAD

**Issue by pulsar14** [akumidv/tradingview-assistant-chrome-extension#51]
I've many params to manage (above 50).
Very often I prefer to jump to the "_Strategy parameters_" window and manage the params directly without doing an export/save before and then import/upload into the addin just to see all the params unchecked apart the ones from the excel file.
When, for example, I change the name or I add a new param in my Strategy and click on "**Test strategy**" without doing before a "Get Template"/"Upload parameters" the "_Strategy parameters_" window opens with ALL the params selected.

So, It might be practical to have **an option at the top of the checkbox column to quickly deselect everything** so that I can only select the parameters I want to test and avoid deselecting all 50 and over parameters by hand first on my list.

**Comment by akumidv** [comment]
Done in new 1.17 version (I'm planning to publish it on this week)
Can you check by manual install from zip file from branch version as described in readme. Direct link https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/heads/v1.17.zip ? 
![image](https://user-images.githubusercontent.com/12490281/200252741-1acbef8c-196d-4589-b466-205cde4220fb.png)

**Comment by akumidv** [comment]
The 2.1 version with fixes has published in webstore
