### ISSUE TITLE
enhancement: Add a button to copy the estimated cycles into the Cycles input-box in "Strategy parameters" popup

### ISSUE THREAD

**Issue by pulsar14** [akumidv/tradingview-assistant-chrome-extension#52]
A helpful button (paste Icon) to copy the estimated cycles value [_id="cyclesAll"_] into the Cycles input box [_id="stratParamCycles"_].

Cycles, by default, is always 10.
Every time, I need to copy by myself the estimated value before to run the Strategy Test.

**Comment by pulsar14** [comment]
![image](https://user-images.githubusercontent.com/14016570/184184407-36ba9c47-e6c2-486a-898b-7163f4f92fec.png)

**Comment by pulsar14** [comment]
1.

**Comment by akumidv** [comment]
Thank you for your suggestions. I can check them and write feedback after my vacation in September.

**Comment by pulsar14** [comment]
> Thank you for your suggestion. I can check them and write feedback after end of my vacation in September.

Thank U very much @akumidv 👍

**Comment by akumidv** [comment]
@pulsar14 Sorry for delay.
Done  In new  1.17 version.
Can you check by manual install from zip file from branch version as described in readme. Direct link https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/heads/v1.17.zip ?
![image](https://user-images.githubusercontent.com/12490281/200225954-67a3fc89-2252-4fa3-a4e7-2203c250c51d.png)

**Comment by akumidv** [comment]
The 2.1 version with fixes has published in webstore

**Comment by pulsar14** [comment]
Great!!!!! Thank you

Kind Regards,
Stefano Scalcinati
________________________________
