### ISSUE TITLE
It Stopped Working!!!

### ISSUE THREAD

**Issue by mradiparmar** [akumidv/tradingview-assistant-chrome-extension#53]
Can you please fix it?? It just stopped working from last 12 hours

**Comment by stefantabakovq** [comment]
Check PR

**Comment by mradiparmar** [comment]
still not working for me I applied all changes and reinstall extension on chrome

**Comment by mradiparmar** [comment]
it does not run the test

**Comment by stefantabakovq** [comment]
> it does not run the test 

Try refresh page of tradingview after re-install?

**Comment by mradiparmar** [comment]
I did every thing but it only takes all parameters but does not run any tests!!
