### ISSUE TITLE
Working patch for UI update proposed as PR

### ISSUE THREAD

**Issue by stefantabakovq** [akumidv/tradingview-assistant-chrome-extension#55]
UI update includes Performance Table update (adding extra table header + table element in body)
Renaming of certain Div's. 

The proposed update is a temporary patch

**Refresh tradingview page after re-install**

**Comment by eXcount** [comment]
It doesn't work at me, press  "Test strategy" and nothing happens...

**Comment by mradiparmar** [comment]
Yup same thing!!

**Comment by stefantabakovq** [comment]
Weird, works for me on 4 seperate PC's. Is your window Fullscreen? Error message?

**Comment by mradiparmar** [comment]
yup did all the things

**Comment by dannydanny77** [comment]
Works for me too, installed as you instructed... Thanks very much.

**Comment by thecao365** [comment]
> Works for me too, installed as you instructed... Thanks very much.

Install here
https://github.com/stefantabakovq/tradingview-assistant-chrome-extension

**Comment by mradiparmar** [comment]
Check issue #56

**Comment by mradiparmar** [comment]
![image](https://user-images.githubusercontent.com/57217179/184525020-a8801136-3421-4153-aeb4-6a2769a74042.png)
IT WORKED ON THIS SIZE WINDOW RATHER THAN FULL SIZE WINDOW!!

**Comment by stefantabakovq** [comment]
That is due to TV changing the performance table with an extra unnecessary column. UI performance headers have 5 columns on Fullscreen, 4 on smaller resolutions @akumidv

**Comment by akumidv** [comment]
Can you check this on version 1.15? I'm on vacation and can check only on my laptop with Full HD screen resolution only.
