### ISSUE TITLE
After Update by admin error

### ISSUE THREAD

**Issue by mradiparmar** [akumidv/tradingview-assistant-chrome-extension#56]
![error](https://user-images.githubusercontent.com/57217179/184468847-9c285963-14db-4e2b-9a4b-6d9bdf47eeb5.png)
this is the error it is throwing after hitting save& run

**Comment by unRekable** [comment]
I get the same error message. Is there any fix for it yet?

**Comment by MrDenfish** [comment]
Oh no, not again..
![Screen Shot 2022-08-14 at 8 29 21 AM](https://user-images.githubusercontent.com/108489215/184546168-21e528c3-652f-4f41-88a3-fe6e60be426a.jpg)
.

**Comment by MrDenfish** [comment]
its not clear but this error was thrown with a full screen as well as a min screen using v1.13.

**Comment by iceman4828** [comment]
So I have tried everything.  I changed the 3 Content Script files.  Tried refreshing, tried unistalling and reinstalling, tried small screen vs full screen.  Nothing worked.  Can you help?

**Comment by duocyber** [comment]
@iceman4828, same here!  Is there any chance that the UI updated will be different from group to group of users.  Sometime I see many Sites will release their features step by step to specific group of users first.

**Comment by akumidv** [comment]
I guess today this error is fixed. But I checked only on my pro+ account and do not know how it will work under premium subscription type. I sent changes to review to google chrome as version 1.15. This version is also available as usual from repository.
