### ISSUE TITLE
Getting this error when trying out a new strategy. Never gotten it before.

### ISSUE THREAD

**Issue by ea2399** [akumidv/tradingview-assistant-chrome-extension#59]
![Screenshot 2022-08-26 085644](https://user-images.githubusercontent.com/112179699/186908764-204254ea-9362-4eeb-9bd0-5330fd37a36c.png)

**Comment by akumidv** [comment]
Thank you, I fixed this error and pushed changes in repository. 
But reason, not in code. The problem there is in setting the strategy parameter – it was empty. I don't know why. From code, it is in a dropdown list.
