### ISSUE TITLE
pageMouseClickEL is not a function

### ISSUE THREAD

**Issue by riodda** [akumidv/tradingview-assistant-chrome-extension#6]
I tryed to run the optimizer on a subset of parameters of a strategy but i randomly get the error pageMouseClickEL is not a function while running.
Does not seems to happen after the same amount of iteration, happens randomly.
![image](https://user-images.githubusercontent.com/13453063/151696077-71daf21c-6284-4354-83cf-fb58fabe2842.png)

**Comment by akumidv** [comment]
> I tryed to run the optimizer on a subset of parameters of a strategy but i randomly get the error pageMouseClickEL is not a function while running. Does not seems to happen after the same amount of iteration, happens randomly. ![image](https://user-images.githubusercontent.com/13453063/151696077-71daf21c-6284-4354-83cf-fb58fabe2842.png)


Thanks a lot. This error is appeared when you use boolean strategy parameters (for checkbox). Fixed. I published the new version 1.2 to Chrome web store today, after review it will be updated in your browser automatically. Can you check?

**Comment by riodda** [comment]
Many thanks, i will give it a run !
