### ISSUE TITLE
new tradingview function-- deep backtesting

### ISSUE THREAD

**Issue by Nise-2-meet-U** [akumidv/tradingview-assistant-chrome-extension#61]
Dear Author:
   How to use this very thoughtful function?

**Comment by MrDenfish** [comment]
This should get you started...
[How to load Tradingview Assistant](https://youtu.be/FH7dI4K8w5k)

**Comment by akumidv** [comment]
> How to use this very thoughtful function? 
I don't have this function on my TV account type. I'll try to check this when it would possible.

**Comment by akumidv** [comment]
> This should get you started... [How to load Tradingview Assistant](https://youtu.be/FH7dI4K8w5k)

Thank you. I added your video to readme.

**Comment by MrDenfish** [comment]
You are welcome, hope it is helpful.

**Comment by akumidv** [comment]
> Dear Author: How to use this very thoughtful function?
User @Murena7 added functional for deep backtesting. It is now on review stage. But you also can test it by download code in zip archive from branch (button code on [page](https://github.com/akumidv/tradingview-assistant-chrome-extension/tree/deep-backtesting) > download zip), install it manually how it described in readme and test how everything are working. 
If you could test and write about problems/sugestions or successful testing results it would be helpful

**Comment by tchit** [comment]
> > Dear Author: How to use this very thoughtful function?
> > User @Murena7 added functional for deep backtesting. It is now on review stage. But you also can test it by download code in zip archive from branch (button code on [page](https://github.com/akumidv/tradingview-assistant-chrome-extension/tree/deep-backtesting) > download zip), install it manually how it described in readme and test how everything are working.
> > If you could test and write about problems/sugestions or successful testing results it would be helpful

Hello,
I installed latest version but I can't find a way to use the deep backtesting with your utility. Is that really possible? Thanks a lot

**Comment by Murena7** [comment]
> > > Dear Author: How to use this very thoughtful function?
> > > User @Murena7 added functional for deep backtesting. It is now on review stage. But you also can test it by download code in zip archive from branch (button code on [page](https://github.com/akumidv/tradingview-assistant-chrome-extension/tree/deep-backtesting) > download zip), install it manually how it described in readme and test how everything are working.
> > > If you could test and write about problems/sugestions or successful testing results it would be helpful
> 
> Hello, I installed latest version but I can't find a way to use the deep backtesting with your utility. Is that really possible? Thanks a lot

Hi, this is possible only if you have Premium subscription plan on the tradingview.com

**Comment by tchit** [comment]
I do have a premium plan. Just can’t make the extension work with the deep backtesting function. Le 5 oct. 2022 à 18:32, Andrew ***@***.***> a écrit :﻿



Dear Author: How to use this very thoughtful function?
User @Murena7 added functional for deep backtesting. It is now on review stage. But you also can test it by download code in zip archive from branch (button code on page > download zip), install it manually how it described in readme and test how everything are working.
If you could test and write about problems/sugestions or successful testing results it would be helpful


Hello, I installed latest version but I can't find a way to use the deep backtesting with your utility. Is that really possible? Thanks a lot

Hi, this is possible only if you have Premium subscription plan on the tradingview.com

**Comment by Vfr123** [comment]
Would it be possible to add more filters?
And I don't know if it is possible (or I don't understand what is written above): optimize Deep Search function with your Assistant. So not only standard period time.

**Comment by Buddingm** [comment]
Hi, I also have premium and like to test deep backtest but also can't find it. Can someone help me?

**Comment by MrDenfish** [comment]
You will need to manually install the latest version.  Go here: https://github.com/akumidv/tradingview-assistant-chrome-extension/tree/deep-backtesting, click the Green "CODE" button, scroll down to Download zip file , save it , unpack it, then "Load Unpacked" within chrome://extensions. You can watch this video that will walk you through the manual install process. The video link to follow shows how to load the deep backtesting file, it should be noted that I cannot get it to work and errors are thrown. It's all documented in the video.  

(https://www.youtube.com/watch?v=e0hPcPtRrSE)

**Comment by Buddingm** [comment]
Hi,

Thanks for the answer.
It works now. I downloaded in first instance the wrong zip file.

Only issue I sometimes have is that the best results are not kept. It then
loads another result after a iterations.

Do you know if we also can get the extra filters and watchlist
possibilities, just like in David's version (strategy helper?)?

Marco

Op wo 12 okt. 2022 00:40 schreef MrDenfish ***@***.***>:

**Comment by Vfr123** [comment]
> Would it be possible to add more filters? And I don't know if it is possible (or I don't understand what is written above): optimize Deep Search function with your Assistant. So not only standard period time.

I found out how it works, great! 

But would it be possible to add more filters? 

Thank you very much for this wonderful  function!

**Comment by oscarjn** [comment]
It works like a charm until it encounter one of the two errors: "The tradingview calculation process has not started for the strategy based on these parameter values" and "The calculation of the strategy parameters took more than 30 seconds for one combination. Testing of this combination is skipped."
Normally the official release skips the combination and goes to the next value of the parameters.
Any idea how to make it ignore the errors and keep testing?

**Comment by akumidv** [comment]
> It works like a charm until it encounter one of the two errors: "The tradingview calculation process has not started for the strategy based on these parameter values" and "The calculation of the strategy parameters took more than 30 seconds for one combination. Testing of this combination is skipped." Normally the official release skips the combination and goes to the next value of the parameters. Any idea how to make it ignore the errors and keep testing?

Implemented in 1.17 version, I'll plan publish it on this week. In new version ptentiall this problem solved.
Can you check by downloading version from branch 1.17 https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/heads/v1.17.zip ?

**Comment by akumidv** [comment]
> Do you know if we also can get the extra filters and watchlist possibilities, just like in David's version (strategy helper?)?

It is not good way to write issue for new function in issue for another problem. I'll think about this, but I do not know how many customers need this function.

**Comment by oscarjn** [comment]
Thanks for the update, downloaded and testing it right now, I will let it run for a few hours and come back with the results.

**Comment by akumidv** [comment]
The 2.1 vesion with fixes has published in webstore
