### ISSUE TITLE
Tradingview changed once again

### ISSUE THREAD

**Issue by DriesVR1232** [akumidv/tradingview-assistant-chrome-extension#62]
This issue speaks for itself, tradingview changed a whole lot again .
![image](https://user-images.githubusercontent.com/32335909/190246694-4149447e-a6fc-4f4a-98bb-75028c762956.png)

**Comment by vulcan4d** [comment]
I just found this extension.  Loaded a strategy and nothing happens when selecting test strategy, not even this error.

**Comment by akumidv** [comment]
Hmm, I tested today on my Pro+ accound and can't get this error. May be tradingview don't finish updates everywhere, I see changes in showing performance graphics, but all worked. 
What type of account do you use? May be this matter.

**Comment by akumidv** [comment]
> This issue speaks for itself, tradingview changed a whole lot again . ![image](https://user-images.githubusercontent.com/32335909/190246694-4149447e-a6fc-4f4a-98bb-75028c762956.png)

Hmm, I tested today on my Pro+ accound and can't get this error. May be tradingview don't finish updates everywhere, I see changes in showing performance graphics, but all worked.
What type of account do you use? May be this matter.

**Comment by DriesVR1232** [comment]
I have premium

**Comment by DriesVR1232** [comment]
yeah nvm it works again..
