### ISSUE TITLE
Maximum duration to extract data from TV

### ISSUE THREAD

**Issue by Bryan3003** [akumidv/tradingview-assistant-chrome-extension#64]
Hi dear developer, really do appreciate the effort on building the strategy assistant. Lately, I have encountered the problem of extracting the data from TV as some of the strategy might take longer loading time (after altering the parameter), which causes the result to be "error". Thus, I am wondering is there any possibility to increase the maximum duration to extract data from TV before it deduced as "error".  

![51738](https://user-images.githubusercontent.com/87373515/190845448-27071fe6-6da1-4f5b-8343-239a82a426fe.png)

**Comment by akumidv** [comment]
> Hi dear developer, really do appreciate the effort on building the strategy assistant. Lately, I have encountered the problem of extracting the data from TV as some of the strategy might take longer loading time (after altering the parameter), which causes the result to be "error". Thus, I am wondering is there any possibility to increase the maximum duration to extract data from TV before it deduced as "error".


Ok, I'll do this in next version.

**Comment by akumidv** [comment]
This is implemented in new 1.17 version.
Can you check by manual install from zip file from branch version as described in readme. Direct link https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/heads/v1.17.zip ?

**Comment by akumidv** [comment]
![Uploading image.png…]()

**Comment by Bryan3003** [comment]
Hi there, really appreciate for the updates. The option for maximum duration data extract is fantastic. It works very well on the deep backtest function, however when using the normal "test strategy" the max duration does not seem to work and start showing error after loading. Can u please have a look on it. Thanks in advances. 
![image](https://user-images.githubusercontent.com/87373515/200592989-c19d1330-526b-4e70-8dec-acf019125638.png)
![image](https://user-images.githubusercontent.com/87373515/200593071-ffde3be1-d0ce-4a6e-bccf-48f7f405b60c.png)
(Purposely set to 120sec to prevent error happens but still...)

**Comment by Bryan3003** [comment]
I suppose the max duration option is only works with deep backtesting?

**Comment by akumidv** [comment]
> I suppose the max duration option is only works with deep backtesting?

In both, but for deep testing it use value from options increased x2 times

**Comment by akumidv** [comment]
> i there, really appreciate for the updates. The option for maximum duration data extract is fantastic. It works very well on the deep backtest function, however when using the normal "test strategy" the max duration does not seem to work and start showing error after loading. Can u please have a look on it. Thanks in advances.

I'll check this again. Thank you.

**Comment by Bryan3003** [comment]
![image](https://user-images.githubusercontent.com/87373515/201082973-4fde1624-d38b-4e2a-97dc-fc34c55d0460.png)
![image](https://user-images.githubusercontent.com/87373515/201084717-bfdd9673-9b71-4066-a0e8-bb25bf14cf6a.png)
 is this what u asking for?

**Comment by akumidv** [comment]
The first screenshot is enough. I'll check this, but from your first screenshot the strategy doesn't finished caclulations.
![image](https://user-images.githubusercontent.com/12490281/202320730-4c1bf3d0-08bc-4aff-ac58-f43e6b24e796.png)
The tradingview have 40 second limit for strategy calculations.

There is something wrong with getting results. So extension can't get results if they do not present on page.
But I guess there have sense add checking if the data loading is still continue. And also instead of undefined results show some message.
