### ISSUE TITLE
Inconsistency Between Optimised Results .CSV and TradingView History

### ISSUE THREAD

**Issue by Earthday12** [akumidv/tradingview-assistant-chrome-extension#65]
Immediately following a cycle, I expected there to be a correlation between the parameters in each row of the .CSV ('Total Closed Trades', 'Percent Profitable'), and what is in the TV history - after running a cycle, when I click 'Undo' in TV, there's often little to no consistency.  E.g. if my results .CSV has one particular cycle with 193 'Total Closed Trades' and 72 'Percent Profitable', I can't find this when going back through the cycles on TV (by clicking 'Undo').  

I know the results .CSV will become redundant with time, as new trades are closed for example, though immediately following a short cycle, I'd expected what was in the results .CSV to match the TV history.

**Comment by akumidv** [comment]
Perhaps this is a feature of your strategy. Users did not create issues about this error. But if you backtesting is quite long and you prepare it on high timeframes it potentially can be.
The results of checking
![image](https://user-images.githubusercontent.com/12490281/200217965-a0186fc5-045c-4b46-a047-55aaabe8ae97.png)
