### ISSUE TITLE
Display best parameters without extracting?

### ISSUE THREAD

**Issue by mtahreemalam** [akumidv/tradingview-assistant-chrome-extension#66]
I assume that extracting the results take part of the speed of extension.
Would it be possible if we only need to see the best parameters without extracting the data to speed up the process?

**Comment by akumidv** [comment]
The process of extracting strategy results depends on the following actions:
- generate a set of strategy parameters (this is fast)
- set these values in the strategy (this is done through the interface and not very fast if there are a lot of parameters in the strategy ~ 10-25%)
- wait for the TV data to be sent to the backend, get and render (70%)
- parse the values and save them (5%) (they used to be taken from the API - but it changes often and it's not stable)

Extracting values is not the slowest operation. There possibly to improve settings parameters, by directly call the TV function - but this takes time to figure out and will probably changing frequently and will not stable.
