### ISSUE TITLE
4 decimals in resulted .csv file

### ISSUE THREAD

**Issue by oscarjn** [akumidv/tradingview-assistant-chrome-extension#67]
Big kudos to developers of this wonderful extension!
What do I have to change in order to have numbers with 4 decimals in the tested parameters columns? When I'm testing values like 0.001, 0.002, 0.003, 0.004 they are shown in the csv as 0 then 0.005, 0.006 are shown as 0.01 ... and so on.
I've tried changing .toFixed(2) to .toFixed(4) but that's not the one lol. I don't know what is it that I'm looking for, I would appreciate any input. Obviously I will change the file locally and load unpacked extension. Thanks a lot!

**Comment by akumidv** [comment]
Really it supported float types. The question was in saving CSV with results. In new 1.17 version it is fixed.
Can you check by manual install from zip file from branch version as described in readme. Direct link https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/heads/v1.17.zip ?

**Comment by oscarjn** [comment]
Yep, working, thanks Andrei.

I will close this now.
