### ISSUE TITLE
Extension Doesn't Support More Than 4 Decimal Digits

### ISSUE THREAD

**Issue by Fiestaman** [akumidv/tradingview-assistant-chrome-extension#69]
Extension doesn't seem to support any values with more than 4 decimal places. Even if I use a step size of 0.000001, the entered parameter by the extension gets rounded to 4 decimal places.

**Comment by TomKaltz** [comment]
#71 may fix this

**Comment by akumidv** [comment]
The @TomKaltz pull request merged and will be published in extension version 1.17 (I'll plan on this week)

**Comment by akumidv** [comment]
Really it supported float types. The question was in saving CSV with results. In new version 1.17 version it is fixed. 
Can you check by manual install from zip file from branch version as described in readme. Direct link https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/heads/v1.17.zip ?

**Comment by akumidv** [comment]
2.1 version with fixes has published in webstore
