### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by riodda** [akumidv/tradingview-assistant-chrome-extension#7]
I'm trading with Jack Rabbit Tradingview suite of signals, it's a cool mudular signal system and normally the alerts are created on the signals and not on the strategies (the strategies are used only to backtest) due to the misfire that normally happens on singals on strategies expecially on fast timeframes.
I wonder is it's possble to use the assistant to change parameters of signals and check thesults on the strategy.
Thanks !

**Comment by akumidv** [comment]
The extension can change the parameters of the indicator in the same way as the parameters of the strategy, there is no problem here. Right now it's just disabled. The only question is how to get the results of these changes. Trading View strategies have special commands for placing orders and closing trades. It is based on them that the backtest results are calculated.
Here is an option to convert the indicator into a strategy. And then you can backtest it.

Or if you know how to take the results from the indicator, when changing the parameters, you need to describe it and then it can be coded.
The extension can be coded to do everything the user does in the Ttrading View interface.

**Comment by riodda** [comment]
JR Framework has a  strategy type module that receives the buy sell signals from the indicators, in this way the the optimizer should change parmeters in indicator and read a strategy module results. This is been done to avoid strategy alert misfire that are common on TV expecially if you go on very fast timeframes.
