### ISSUE TITLE
Tradingview site changed

### ISSUE THREAD

**Issue by DriesVR1232** [akumidv/tradingview-assistant-chrome-extension#70]
its that time again. They changed their website. A friend and i both have this issue so i assume others will have this too.
![image](https://user-images.githubusercontent.com/32335909/198882443-eb70dd76-2949-4ec1-ba92-a71d88b9cad0.png)

**Comment by MrDenfish** [comment]
No issues for me.
Chrome Version 106.0.5249.119 (Official Build) (x86_64)
Tradingview 1.16

Working great, maybe try to manually uninstall the TV extension then manually install.
[https://github.com/akumidv/tradingview-assistant-chrome-extension]
Scroll to the bottom of the page for a step by step how to.

Good luck

**Comment by akumidv** [comment]
> its that time again. They changed their website. A friend and i both have this issue so i assume others will have this too. ![image](https://user-images.githubusercontent.com/32335909/198882443-eb70dd76-2949-4ec1-ba92-a71d88b9cad0.png)

It would be helpful if you take screenshot with full TV screen and when the browser console is opened (F12). The error didn't repeat when I tested.
