### ISSUE TITLE
Please can you add the option of a time delay between each iteration

### ISSUE THREAD

**Issue by rshokar77** [akumidv/tradingview-assistant-chrome-extension#72]
please add the option of a time delay before the extension runs each iteration, as this will make it impossible for trading view to ban you for suspicious activites. Other optimisers have the delay as default 250ms but users can put it higher if they want to. Having the default as 250ms means that users will not get banned by trading view for suspicious activites

**Comment by akumidv** [comment]
Added delay that can be set in seconds with decimal point forms in new 1.17 version (planned for publishing on this week)
Can you check by manual install from zip file in version branch as described in readme https://github.com/akumidv/tradingview-assistant-chrome-extension/archive/refs/heads/v1.17.zip ?
![image](https://user-images.githubusercontent.com/12490281/200216656-31b88acd-012b-4dbe-b5f0-f9c713220f0a.png)

**Comment by rshokar77** [comment]
Yes all good! Thank you for the kind work Sir, you are really helping out a lot of people by putting your best efforts into this project and making it publicly available for free. Your work will always be appreciated by everyone, even if they don't necessarily say it :)

**Comment by akumidv** [comment]
2.1 version with fixes has published in webstore
