### ISSUE TITLE
TRADEINGVIWER UI  CHANGED

### ISSUE THREAD

**Issue by blacksmith2022** [akumidv/tradingview-assistant-chrome-extension#73]
CAN'T GET PERFORMANCE HEADERS .

**Comment by akumidv** [comment]
I can't reproduce. What is the version you use and can you take screenshoot?

**Comment by blacksmith2022** [comment]
SORRY ABOUT THAT I JUST GOT IT WORKING 2MINS AGO AFTER TRYING ALL WEEK THANK MAN YOU DO GREAT WORK .

**Comment by blacksmith2022** [comment]
I WAS USING THE OUT-OF-DATE ONE BY DAVE TEC [chrome web store](https://chrome.google.com/webstore/category/extensions).

**Comment by blacksmith2022** [comment]
NOW I HAVE THE NEW ONE YOU UPDATED. THANKS AGAIN.
