### ISSUE TITLE
The Optimizer unable to load initial parameter 

### ISSUE THREAD

**Issue by Bryan3003** [akumidv/tradingview-assistant-chrome-extension#79]
The Optimizer doesn't load after selecting "save & run" 
![image](https://user-images.githubusercontent.com/87373515/201705519-b3e933bd-ab2f-4bf6-ae24-97f9052fcf3b.png)
Any reason it might cause this to happen? It used to work well when 1.17 just released.

**Comment by akumidv** [comment]
This problem solved in version 2.1 - the reason in TV UI changes for performance report table.

**Comment by akumidv** [comment]
2.1 version with fixes has published in webstore
