### ISSUE TITLE
It doesn't start calculation. It keeps always "get initial parameters".

### ISSUE THREAD

**Issue by Senpan2022** [akumidv/tradingview-assistant-chrome-extension#83]
Hello,

It keeps always in "get initial parameters" screen since yesterday evening. Could you help me?

Thanks,

**Comment by texmex44** [comment]
Same error here

**Comment by PhantomFFP** [comment]
Download the latest version, that fixes the problem

![image](https://user-images.githubusercontent.com/74529353/201902516-f5027f90-22b9-4fed-8ac2-9d41bb4739e9.png)


Download: [https://github.com/akumidv/tradingview-assistant-chrome-extension/releases/tag/v2.1](url)

**Comment by Senpan2022** [comment]
Thanks! it works perfect with the new version!!

**Comment by akumidv** [comment]
I sent yesterday version v2.1 to Google WebStore review, so after this it would publish automatically. Just wait if you can't install manually.

**Comment by akumidv** [comment]
2.1 version with fixes has published in webstore
