### ISSUE TITLE
2.0 DOSE NOT WANT TO GET THE INITIAL PARAMETERS ON START UP .

### ISSUE THREAD

**Issue by blacksmith2022** [akumidv/tradingview-assistant-chrome-extension#84]
NOT TO TAKE ANYTHING AWAY FORM THE NEW SETTINGS  I LOVE WHAT YOU HAVE DONE . ITS NOT RUNING AT ALL NOW . IVE BEEN PLAYING AROUND WHIT IT  FOR 2HRS NOW STILL CANT RUN TEST.

**Comment by PhantomFFP** [comment]
https://github.com/akumidv/tradingview-assistant-chrome-extension/issues/83#issuecomment-1315137921

**Comment by blacksmith2022** [comment]
I DONT KNOW HOW THE ZIP FILE  WILL FIX IT .I AM USING THE CROME PLUG IN

**Comment by akumidv** [comment]
The instruction how ti install extension manually present in readme. This problem of Monday TradingView UI changes solved in version 2.1  and it sent to review to Google WebStore so it would publish after this
