### ISSUE TITLE
WELL I KNOW ITS JUST NOT MY COMPUTER THEN LOL BUT YEA IAM HAVEING THE SAME THING GO ON.

### ISSUE THREAD

**Issue by blacksmith2022** [akumidv/tradingview-assistant-chrome-extension#85]
IAM SURE IT A QUICK FIX.

**Comment by triton2030** [comment]
Omg you didn't pay for this to demand something.
And about your problem, something wrong with your PC.
Works fine for me

**Comment by akumidv** [comment]
The title and you comment do not describe the problem. Please describe it or the issue will be closed in few days.

**Comment by akumidv** [comment]
I've got t- his issue is repeat of previous one. Closed.
