### ISSUE TITLE
runtime.lastError - could not establish connection. 

### ISSUE THREAD

**Issue by villa-leone** [akumidv/tradingview-assistant-chrome-extension#86]
![error](https://user-images.githubusercontent.com/118316292/202041363-f7b6acde-9a04-4f93-997f-11c35a36b5bd.PNG)

issue occurs when i attempt to test a strategy. extension loads fine and is viewable, but i cant seem to figure this out :(

Appreciate any help, i enjoy this extension thoroughly :)

**Comment by akumidv** [comment]
The problems seem appeared when you click on tab on poppup. May be samething wrong in automatically updates from webstore. 

Possible there two solution can be on  reinstall extension (delete it and install again)

Or can you test on another browser: Brave, Vivaldi and a lot of based on Chrominium.

From this error is hard to say more. If you click right button of mouse on extension popup and choose "Inspect" it would open the browser developer window. Open please console tab and when this error reproduced - please take screenshot with error on console tab.

**Comment by greg-pantaleone** [comment]
unpacking from git directly have tried reinstalling through setup steps several times. when inspecting i found this 
![image](https://user-images.githubusercontent.com/118316292/202095972-765b9e39-6712-4e42-9569-9e9c52388c1b.png)
does it need a url to connect with in the popup/assistant.html file?

**Comment by akumidv** [comment]
Try another browse without another extension. Probably there can be some protection on you computer, you can try to temporary turn it off or run on another comuter, or probably in virtual machine if there some strict restriction where you try. The extension work under all chromimun based browsers in any operation systems. For example I'm testing it under Fedora/Ubuntu.
