### ISSUE TITLE
Deep Backtesting no longer works

### ISSUE THREAD

**Issue by vehct0r** [akumidv/tradingview-assistant-chrome-extension#95]
Hello,
As of recently the addon does not properly work with deep backtesting, and yes I do have a current subscription to Tradingview Premium. Any insight would be appreciated

**Comment by VincenzoUrso** [comment]
have you tried reloading the page? often deep backtesting goes "stuck" and the extension is not able to read the values

**Comment by Buddingm** [comment]
I have indeed the same problem.

**Comment by vehct0r** [comment]
Had to clear cookies from tradingview got it working

**Comment by Buddingm** [comment]
Wow, that is great. I will check if that works here also.

**Comment by Buddingm** [comment]
Tried a lot here. Clearing cookies, different filters and settings but that does not help here
