### ISSUE TITLE
Fix for plugin "Strategy not found" 02/23/2023

### ISSUE THREAD

**Issue by stefantabakovq** [akumidv/tradingview-assistant-chrome-extension#98]
This error is happening because of a change in the paths on TradingView's side. 

Change CSS selectors in content_scripts > selector.js to:
 `strategyTesterTab: '#bottom-area > div.bottom-widgetbar-content.backtesting'`
....
`strategyCaption: '#bottom-area div[class^="backtesting"]  [class^="strategyGroup"] div[data-strategy-title]'`

note that `data-qa-strategy-title` is now `data-strategy-title`

**Comment by kypexin** [comment]
UPDATE: now it worked. 
Mystery, and many thanks for your help.

**Comment by dayu998** [comment]
非常感谢！

**Comment by VincenzoUrso** [comment]
how to do that?

**Comment by stefantabakovq** [comment]
> how to do that?

Download files (zip), edit content _files > selector.js with the changes above, then go to 'chrome://extensions' > Load unpacked and select files folder. Remove old version first though (it will wipe your settings unfortunately)

**Comment by akumidv** [comment]
The problem is fIxed in the new 2.2 version that was send to Google for review before publishing
